#!/usr/bin/env bash

# New user creation utility.

function create-user() {
  local user="${1:-}";
  local pass="${2:-}";

  if [[ -z "${user}" || -z "${pass}" ]]; then
    return 1; fi; # Missing required arg(s).

  if user-exists "${user}"; then
    return 1; fi; # User exists!

  if group-exists "${user}"; then
    useradd "${user}" -g "${user}" --create-home;
  else # Create a group matching the username.
    useradd "${user}" --user-group --create-home;
  fi;
  echo "${user}"':'"${pass}" | chpasswd;
};
