#!/usr/bin/env bash
# For sheckcheck ↑ only.

# Prompt handler.

function precmd() {
  PROMPT='%F{002}'"$(whoami)";
  PROMPT+='%f@%F{006}'"$(hostname --long)";
  PROMPT+='%f['"${PWD}"']'$'\n';
  PROMPT+='%F{002}$ ';
  PROMPT+='%f';

  RPROMPT='%F{002}'"$(whoami)";
  RPROMPT+='%f@%F{006}'"$(hostname --long)";
  is-vm && RPROMPT+='%f (VM)' || RPROMPT+='';
  RPROMPT+='%f';
};
