#!/usr/bin/env bash
# For sheckcheck ↑ only.

# Prompt handler.

function precmd() {
  PROMPT='%F{002}'"$(whoami)";
  PROMPT+='%F{240}@%F{006}'"$(hostname --long)";
  PROMPT+='%F{233}[%F{240}'"${PWD}"'%F{233}]'$'\n';
  PROMPT+='%F{002}$ ';
  PROMPT+='%f';

  RPROMPT='%F{002}'"$(whoami)";
  RPROMPT+='%F{240}@%F{006}'"$(hostname --long)";
  is-vm && RPROMPT+='%F{240} (VM)' || RPROMPT+='';
  RPROMPT+='%f';
};
