#!/usr/bin/env bash

# Sanity checks. Right location? Running as sudo?

if [[ "${BASH_SOURCE[0]}" != '/bootstrap/installer-4ci' ]]; then
  echo 'I must live in the /bootstrap directory.'; exit 1;
elif [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Maybe run setup routines; i.e., once only.

if [[ ! -f /etc/bootstrap/.installed ]]; then
  /bootstrap/installer --CFG_USE_WIZARD=0;
fi;
# Build a CI image inside a Docker container now.

php_version='custom'; # Default value.
short_options=''; long_options='php-version:';
options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";

eval set -- "${options}"; while true; do
   case "${1}" in
      --php-version)
        php_version="${2}";
        shift 2;
        ;;
      --) shift 1; break;
        ;;
      *) echo 'Internal error.'; exit 1;
        ;;
   esac;
done;

bootstrap=$(cat <<'_'
  export _4CI=true;

  export DEBIAN_FRONTEND=noninteractive;

  apt-get install git --yes;
  git clone https://github.com/websharks/ubuntu-bootstrap --branch=master --depth=1 /bootstrap;

  cd /bootstrap;
  git checkout -b "$(hostname --long)";
_
);
bootstrap+=$(cat <<_
  /bootstrap/installer --CFG_USE_WIZARD=0 --CFG_INSTALL_PHP_VERSION="${php_version}";
_
);
docker run --hostname=ci.vm --name=websharks-ubuntu-bootstrap-ci-php-"${php_version}" phusion/baseimage /usr/bin/env bash -c "${bootstrap}";
docker commit -m 'Creating image.' -a 'websharks-ubuntu-bootstrap' websharks-ubuntu-bootstrap-ci-php-"${php_version}" websharks/ubuntu-bootstrap-ci-php-"${php_version}";
echo 'Run `$ docker login` and then `$ docker push websharks/ubuntu-bootstrap-ci-php-'"${php_version}"'` to upload the container image that was just commited locally.';
