#!/usr/bin/env bash

# This script runs on YOUR system after a `vagrant up`.
# i.e., it does not run on the VM like `vg-bootstrap` does.

# Include strict mode & functions.

. "$(dirname "${BASH_SOURCE[0]}")"/src/bash/strict-mode;
. "$(dirname "${BASH_SOURCE[0]}")"/src/bash/functions;

# Maybe flush the DNS cache to avoid problems.

if [[ "${OSTYPE}" == 'darwin'* ]]; then
  echo 'Flushing DNS on Mac OS X; requires sudo...';
  sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder;
fi;
