#!/usr/bin/env bash

memcached='memcached'; while read -r _line; do
  if [[ "${_line}" =~ ^\- && "${_line}" != '-d' && ! "${_line}" =~ ^\-u ]]; then
    memcached+=' '"${_line}"; fi;
done < /etc/memcached.conf; unset _line;

exec setuser memcache "${memcached}" >> /var/log/memcached.log 2>&1;
