#!/usr/bin/env bash

options=''; while read -r _line; do
  if [[ "${_line}" =~ ^\- && "${_line}" != '-d' && ! "${_line}" =~ ^\-u ]]; then
    if [[ -n "${options}" ]]; then
      options+=' '"${_line}";
    else options+="${_line}"; fi;
  fi;
done < /etc/memcached.conf; unset _line;

exec setuser memcache /usr/bin/memcached "${options}" >> /var/log/memcached.log 2>&1;
