#!/usr/bin/env bash

options=''; while read -r _line; do
  if [[ "${_line}" =~ ^\- && "${_line}" != '-d' ]]; then
    options+=' '"${_line}"; fi;
done < /etc/memcached.conf; unset _line;

exec memcached "${options}" 2>&1;
