#!/usr/bin/env bash

# Function includes.
# shellcheck disable=SC1090

for _file in "$(dirname "${BASH_SOURCE[0]}")"/funcs/**; do
  [[ -f "${_file}" ]] && . "${_file}";
done; unset _file;

# Process CFGs.

process-cfgs; unset cfgs;
