#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Maybe create theme symlinks.

if [[ -d /app/src/wp-content/themes ]]; then
  for _wp_dir in /wp-projects /wp-personal /wp-business; do

    if [[ -d "${_wp_dir}"/themes ]]; then
      for _dir in "${_wp_dir}"/themes/*; do

        if [[ -d "${_dir}"/"$(basename "${_dir}")" ]]; then
          rm --force /app/src/wp-content/themes/"$(basename "${_dir}")";
          ln --symbolic --no-target-directory "${_dir}"/"$(basename "${_dir}")" /app/src/wp-content/themes/"$(basename "${_dir}")";
        elif [[ -d "${_dir}" ]]; then
          rm --force /app/src/wp-content/themes/"$(basename "${_dir}")";
          ln --symbolic --no-target-directory "${_dir}" /app/src/wp-content/themes/"$(basename "${_dir}")";
        fi;

      done; unset _dir;
    fi; # Housekeeping.

  done; unset _wp_dir;
fi; # Housekeeping.

# Maybe create plugin symlinks.

if [[ -d /app/src/wp-content/plugins ]]; then
  for _wp_dir in /wp-projects /wp-personal /wp-business; do

    if [[ -d "${_wp_dir}"/plugins ]]; then
      for _dir in "${_wp_dir}"/plugins/*; do

        if [[ -d "${_dir}"/"$(basename "${_dir}")" ]]; then
          rm --force /app/src/wp-content/plugins/"$(basename "${_dir}")";
          ln --symbolic --no-target-directory "${_dir}"/"$(basename "${_dir}")" /app/src/wp-content/plugins/"$(basename "${_dir}")";
        elif [[ -d "${_dir}" ]]; then # Not in a nested sub-directory; i.e., this is the plugin directory?
          rm --force /app/src/wp-content/plugins/"$(basename "${_dir}")";
          ln --symbolic --no-target-directory "${_dir}" /app/src/wp-content/plugins/"$(basename "${_dir}")";
        fi;

      done; unset _dir;
    fi; # Housekeeping.

  done; unset _wp_dir;
fi; # Housekeeping.
