#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Start from a clean `/app/src`.

mkdir --parents /app/src;
rm --force --recursive /app/src/*;

# Install the latest version of WordPress.

curl http://wordpress.org/latest.zip --location --output /tmp/wordpress-latest.zip;
unzip -qq -d /tmp/wordpress-latest /tmp/wordpress-latest.zip;
cp --force --recursive --preserve=all /tmp/wordpress-latest/wordpress/. /app/src;

rm --force --recursive /tmp/wordpress-latest;
rm --force /tmp/wordpress-latest.zip;

# Maybe setup a `/wp-config.php` file.

if is-vm || is-dev; then # Only for VMs and/or dev test sites.
  cp /bootstrap/src/wordpress/dev/wp-config.php /app/src/wp-config.php;

  perl -i -0wpe 's/%%CFG_MYSQL_DB_HOST%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_HOST}")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%CFG_MYSQL_DB_PORT%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_PORT}")"'/ug' /app/src/wp-config.php;

  perl -i -0wpe 's/%%CFG_MYSQL_DB_CHARSET%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_CHARSET}")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%CFG_MYSQL_DB_COLLATE%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_COLLATE}")"'/ug' /app/src/wp-config.php;

  perl -i -0wpe 's/%%CFG_MYSQL_DB_USERNAME%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_USERNAME}")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%CFG_MYSQL_DB_PASSWORD%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_PASSWORD}")"'/ug' /app/src/wp-config.php;

  perl -i -0wpe 's/%%CFG_MYSQL_DB_NAME%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_NAME}")"'/ug' /app/src/wp-config.php;

  perl -i -0wpe 's/%%AUTH_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%SECURE_AUTH_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%LOGGED_IN_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%NONCE_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%AUTH_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%SECURE_AUTH_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%LOGGED_IN_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;
  perl -i -0wpe 's/%%NONCE_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/ug' /app/src/wp-config.php;

  if is-vm; then # We can disable the dev guard on a VM.
    perl -i -wpe 's/^(\s*require_once\s*'"'"'\/bootstrap\/src\/wordpress\/dev\/guard\.php'"'"'\s*;\s*)$/#$1/ui' /app/src/wp-config.php;
  fi;
fi;
# Setup the WordPress installation guard key.

perl -i -0wpe 's/%%CFG_MAINTENANCE_BYPASS_KEY%%/'"$(esc-regex-rv "${CFG_MAINTENANCE_BYPASS_KEY}")"'/ug' /bootstrap/src/wordpress/dev/guard.php;

# Maybe setup a `robots.txt` file.

if is-vm || is-dev; then # VMs and/or dev test sites.
  # Setup a `robots.txt` file to disallow all search engines.
  ln --symbolic /bootstrap/src/wordpress/dev/robots.txt /app/src/robots.txt;
fi;
# Set permissions in the `/app/src` directory.

chown --recursive www-data:app /app/src;
find /app/src -type d -exec chmod 2775 {} \;
find /app/src -type f -exec chmod 664 {} \;

# Start with a brand new database; i.e., drop if exists and create.

mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DROP DATABASE IF EXISTS \`${CFG_MYSQL_DB_NAME}\`;";
mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="CREATE DATABASE IF NOT EXISTS \`${CFG_MYSQL_DB_NAME}\` CHARACTER SET '${CFG_MYSQL_DB_CHARSET}' COLLATE '${CFG_MYSQL_DB_COLLATE}';";

# Stop w/ a success message to the operator.

echo '---------------------------------------------------------------';
echo '-- WordPress installation complete. ---------------------------';
echo '---------------------------------------------------------------';
