#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# PHP configuration file.

ln --symbolic /bootstrap/src/wordpress/install-dev-extras.ini "${PHP_INI_DIR}"/conf.d/z90.ini;

# Install the XDebug extension for testing.

pecl install xdebug &>/dev/null; # Quiety to avoid confusion on rebuilds.
echo 'zend_extension="'"$(php-config --extension-dir)"'/xdebug.so"' > "${PHP_INI_DIR}"/conf.d/xdebug.ini;
