#!/usr/bin/env bash
# shellcheck disable=SC2153

# Finalize & rectify config. vars.

function cfgs-finalize-rectify() {
  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_DOCKER}" != 1 ]]; then
    CFG_INSTALL_WORDPRESS_DEV_CONTAINERS='0';
    CFG_INSTALL_DISCOURSE='0';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_MYSQL}" != 1 ]]; then
    CFG_MYSQL_DB_HOST='';
    CFG_MYSQL_DB_PORT='';

    CFG_MYSQL_SSL_KEY='';
    CFG_MYSQL_SSL_CRT='';
    CFG_MYSQL_SSL_CA='';
    CFG_MYSQL_SSL_CIPHER='';

    CFG_MYSQL_SSL_ENABLE='0';

    CFG_MYSQL_DB_CHARSET='';
    CFG_MYSQL_DB_COLLATE='';

    CFG_MYSQL_DB_NAME='';

    CFG_MYSQL_DB_USERNAME='';
    CFG_MYSQL_DB_PASSWORD='';

    CFG_MYSQL_X_DB_USERNAME='';
    CFG_MYSQL_X_DB_PASSWORD='';

    CFG_MYSQL_X_REQUIRES_SSL='0';

    CFG_INSTALL_PMA='0';
    CFG_FIREWALL_ALLOWS_MYSQL_VIA_3306='0';
    CFG_FIREWALL_ALLOWS_MYSQL_INSIDE_VPN='0';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_PHP_CLI}" != 1 ]]; then
    CFG_INSTALL_PSYSH='0';
    CFG_INSTALL_PHPCS='0';
    CFG_INSTALL_PHING='0';
    CFG_INSTALL_PHPUNIT='0';
    CFG_INSTALL_SAMI='0';
    CFG_INSTALL_APIGEN='0';
    CFG_INSTALL_COMPOSER='0';
    CFG_INSTALL_WP_CLI='0';
    CFG_INSTALL_WP_I18N_TOOLS='0';
    CFG_INSTALL_WEBSHARKS_CORE='0';
  fi;
  if [[ "${CFG_INSTALL_PHP_FPM}" != 1 ]]; then
    CFG_INSTALL_NGINX='0';
    CFG_INSTALL_APACHE='0';

    CFG_INSTALL_PMA='0';
    CFG_INSTALL_CACHETOOL='0';

    CFG_INSTALL_WORDPRESS='0';
  fi;
  if [[ "${CFG_INSTALL_PHP_CLI}" != 1 && "${CFG_INSTALL_PHP_FPM}" != 1 ]]; then
    CFG_INSTALL_PHP_VERSION='';

    CFG_ENABLE_PHP_OPCACHE='0';
    CFG_INSTALL_PHP_XDEBUG='0';
    CFG_ENABLE_PHP_PHAR_READONLY='0';
    CFG_ENABLE_PHP_ASSERTIONS='0';
  fi;
  if [[ "${CFG_ENABLE_PHP_OPCACHE}" != 1 ]]; then
    CFG_INSTALL_CACHETOOL='0';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_COMPOSER}" != 1 ]]; then
    CFG_INSTALL_PMA='0';
  fi;
  if [[ "${CFG_INSTALL_PMA}" != 1 ]]; then
    CFG_PMA_BLOWFISH_KEY='';
  fi;
  if [[ "${CFG_INSTALL_PHING}" != 1 ]]; then
    CFG_INSTALL_WEBSHARKS_CORE='0';
    CFG_INSTALL_APP_REPO='0';
  fi;
  if [[ -z "${CFG_INSTALL_PHP_VERSION}" ]] || version-compare "${CFG_INSTALL_PHP_VERSION}" lt 7; then
    CFG_INSTALL_WEBSHARKS_CORE='0';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_NGINX}" != 1 && "${CFG_INSTALL_APACHE}" != 1 ]]; then
    CFG_WEB_SERVER_SSL_ONLY='0';
    CFG_MAINTENANCE_BYPASS_KEY='';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_WORDPRESS}" != 1 ]]; then
    CFG_INSTALL_WORDPRESS_VM_SYMLINKS='0';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_WORDPRESS_DEV_CONTAINERS}" != 1 || -z "${CFG_WORDPRESS_DEV_USERNAME}" ]]; then
    CFG_WORDPRESS_DEV_GENDER='';

    CFG_WORDPRESS_DEV_USERNAME='';
    CFG_WORDPRESS_DEV_PASSWORD='';

    CFG_WORDPRESS_DEV_NAME='';
    CFG_WORDPRESS_DEV_EMAIL='';

    CFG_WORDPRESS_DEV_PREFERRED_SHELL='';
    CFG_WORDPRESS_DEV_STATIC_IP_ADDRESS='';
    CFG_WORDPRESS_DEV_AUTHORIZED_SSH_KEYS='';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_DISCOURSE}" != 1 ]]; then
    CFG_DISCOURSE_SMTP_HOST='';
    CFG_DISCOURSE_SMTP_PORT='';

    CFG_DISCOURSE_SMTP_AUTH_TYPE='';
    CFG_DISCOURSE_SMTP_USERNAME='';
    CFG_DISCOURSE_SMTP_PASSWORD='';
  fi;

  # --------------------------------------------------------------------------------------------------------------------

  if [[ "${CFG_INSTALL_FIREWALL}" != 1 ]]; then
    CFG_FIREWALL_ALLOWS_ADMIN_ONLY_VIA_22='0';
    CFG_FIREWALL_ALLOWS_MYSQL_VIA_3306='0';
    CFG_FIREWALL_ALLOWS_MYSQL_INSIDE_VPN='0';
    CFG_FIREWALL_ALLOWS_CF_ONLY_VIA_80_443='0';
  fi;
};
