#!/usr/bin/env bash

if [[ "${CFG_INSTALL_PHP}" == 1 && "${CFG_INSTALL_PHP_VERSION}" =~ ^custom ]]; then

  ## Enable the igbinary extension.

  ## @TODO Once it supports PHP7.
  #echo 'extension=igbinary.so' > /etc/php/conf.d/igbinary.ini;
  #ln --symbolic /etc/php/conf.d/igbinary.ini /etc/php/cli/conf.d/igbinary.ini;
  #ln --symbolic /etc/php/conf.d/igbinary.ini /etc/php/fpm/conf.d/igbinary.ini;

  # Restart service.

  service php-fpm restart;

else echo 'Skipping igBinary extension for custom PHP.'; fi;
