#!/usr/bin/env php
<?php
declare(strict_types=1);
namespace WebSharks\Ubuntu\Bootstrap\Crons;

use WebSharks\Core\Classes\CoreFacades as c;

require_once '/usr/local/src/websharks-core/src/includes/app-stub.php';

$Config        = c::app()->Config;
$php_error_log = '/var/log/php/errors.log';

if (is_file($php_error_log) && filesize($php_error_log)) {
    c::email(
        $Config->©contacts['©admin']['©email'],
        'PHP Errors @ '.$Config->©urls['©hosts']['©app'],
        'PHP Errors @ '.$Config->©urls['©hosts']['©app'],
        [$php_error_log]
    );
    file_put_contents($php_error_log, '');
}
