#!/usr/bin/env php
<?php
declare (strict_types = 1);
namespace WebSharks\Ubuntu\Bootstrap\Crons;

use WebSharks\Core\Classes\AppFacades as a;

require_once '/usr/local/src/wsc/src/includes/app-stub.php';

$Config        = a::app()->Config;
$php_error_log = '/var/log/php/errors.log';

if (is_file($php_error_log) && filesize($php_error_log)) {
    a::email(
        $Config->contacts['admin']['email'],
        'PHP Errors @ '.$Config->urls['hosts']['app'],
        'PHP Errors @ '.$Config->urls['hosts']['app'],
        [$php_error_log]
    );
    file_put_contents($php_error_log, '');
}
