#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Link the `/vagrant` directory to `/bootstrap`.

if [[ ! -d /bootstrap && -d /vagrant ]]; then
  ln --symbolic /vagrant /bootstrap; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Run any custom code now.

. /bootstrap/src/vagrant/bootstrap-custom;
