#!/usr/bin/env bash

# Include strict mode & functions.

_bootstrap_dir="$(dirname "${BASH_SOURCE[0]}")";
_bootstrap_dir="$(dirname "${_bootstrap_dir}")";
_bootstrap_dir="$(dirname "${_bootstrap_dir}")";

. "${_bootstrap_dir}"/src/bash/strict-mode;
. "${_bootstrap_dir}"/src/bash/functions;

unset _bootstrap_dir; # Housekeeping.

# Maybe flush the DNS cache to avoid problems.

if [[ "${OSTYPE}" == 'darwin'* ]]; then
  echo 'Flushing DNS on Mac OS X; requires sudo ...';
  sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder;
fi;
