#!/usr/bin/env bash

# Strict mode.

set -o nounset;
set -o errexit;
set -o errtrace;
set -o pipefail;

# Maybe flush the DNS cache.

if [[ "${OSTYPE}" == 'darwin'* ]]; then
  echo 'Flushing DNS on Mac OS X; requires sudo ...';
  sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder;
fi;
