#!/usr/bin/env bash

if [[ "${CFG_INSTALL_APACHE}" == 1 ]]; then

  # Install Apache web server.

  apt-get install apache2 --yes;
  apt-get install libapache2-mod-fastcgi --yes;

  # Configure Apache web server.

  a2dismod autoindex -f;
  a2dismod negotiation -f;
  a2dissite 000-default;

  a2enmod mpm_event;

  a2enmod auth_basic;

  a2enmod authn_core;
  a2enmod authn_file;

  a2enmod authz_core;
  a2enmod authz_host;
  a2enmod authz_user;

  a2enmod env;
  a2enmod setenvif;

  a2enmod ssl;
  a2enmod socache_shmcb;

  a2enmod dir;
  a2enmod alias;
  a2enmod vhost_alias;
  a2enmod rewrite;

  a2enmod mime;
  a2enmod actions;
  a2enmod fastcgi;

  a2enmod expires;
  a2enmod headers;

  a2enmod deflate;
  a2enmod filter;

  a2enmod info;
  a2enmod status;

  a2enmod access_compat;

  mkdir --parents /var/bootstrap/cgi-bin;
  ln --symbolic /bootstrap/src/apache/.conf /etc/apache2/conf-enabled/z90.conf;

  if is-vm; then # Disable sendfile on VMs.
    perl -i -wpe 's/^(\s*)EnableSendfile\s+.*$/$1EnableSendfile off/ui' /bootstrap/src/apache/.conf;
  fi; # See: <https://docs.vagrantup.com/v2/synced-folders/virtualbox.html>

  # Tack our `CFG_` vars onto the existing environment vars.
  cat /etc/apache2/~envvars >> /etc/apache2/envvars; rm /etc/apache2/~envvars;

  # Maybe create an RUnit startup script.

  if in-docker && can-run sv; then
    mkdir --parents /etc/service/apache2;
    ln --symbolic /bootstrap/src/docker/runit/apache2 /etc/service/apache2/run;
  fi;
  # Put live sites into maintenance mode by default.

  if ! is-vm; then
    touch /app/.maintenance; fi;

  # Restart service.

  service apache2 restart;

else echo 'Skipping Apache installation.'; fi;
