#!/usr/bin/env bash

# Update.

apt-get update --yes;
# Force new config files; see: <http://jas.xyz/2cDOeXI>
apt-get upgrade --yes --option 'Dpkg::Options::=--force-confnew';

# Install APT dependencies.

apt-get install ca-certificates --yes;
apt-get install apt-transport-https --yes;
apt-get install software-properties-common --yes;

# Set an english/UTF-8 locale.

apt-get install language-pack-en-base --yes;
export LC_ALL=en_US.UTF-8; export LANG=en_US.UTF-8;

# Add multiverse repo.

apt-add-repository multiverse --yes;
apt-get update; # Update again.

# Setup automatic security updates.

if [[ "${CFG_INSTALL_UNATTENDED_UPGRADES}" == 1 ]]; then

  apt-get install unattended-upgrades --yes;
  apt-get install update-notifier-common --yes;

  mv /etc/apt/apt.conf.d/10periodic /tmp/apt-10periodic~;
  mv /etc/apt/apt.conf.d/50unattended-upgrades /tmp/apt-50unattended-upgrades~;

  ln --symbolic /bootstrap/src/apt/periodic /etc/apt/apt.conf.d/10periodic;
  ln --symbolic /bootstrap/src/apt/upgrades /etc/apt/apt.conf.d/50unattended-upgrades;

  perl -i -0wpe 's/%%email%%/'"$(esc-regex-rv "${CFG_ADMIN_EMAIL}")"'/ug' /bootstrap/src/apt/upgrades;

else echo 'Skipping installation of unattended-upgrades package.'; fi;
