#!/usr/bin/env bash

# Update.

apt-get update --yes;
# Force new config files; see: <http://jas.xyz/2cDOeXI>
apt-get upgrade --yes --option 'Dpkg::Options::=--force-confnew';

# Install APT dependencies.

apt-get install ca-certificates --yes;
apt-get install apt-transport-https --yes;
apt-get install software-properties-common --yes;

# Set an english/UTF-8 locale.

apt-get install language-pack-en-base --yes;
export LC_ALL=en_US.UTF-8; export LANG=en_US.UTF-8;

# Add multiverse repo.

apt-add-repository multiverse --yes;
apt-get update; # Update again.

# Setup automatic security updates.

if [[ "${CFG_INSTALL_UNATTENDED_UPGRADES}" == 1 ]]; then

  apt-get install unattended-upgrades --yes;

  echo 'Unattended-Upgrade::Automatic-Reboot "true";' >> /etc/apt/apt.conf.d/50unattended-upgrades;
  echo 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' >> /etc/apt/apt.conf.d/50unattended-upgrades;

  echo 'APT::Periodic::Update-Package-Lists "1";' > /etc/apt/apt.conf.d/10periodic;
  echo 'APT::Periodic::Download-Upgradeable-Packages "1";' >> /etc/apt/apt.conf.d/10periodic;
  echo 'APT::Periodic::AutocleanInterval "7";' >> /etc/apt/apt.conf.d/10periodic;
  echo 'APT::Periodic::Unattended-Upgrade "1";' >> /etc/apt/apt.conf.d/10periodic;

else echo 'Skipping installation of unattended-upgrades package.'; fi;
