#!/usr/bin/env bash

# Non-interactive.

export DEBIAN_FRONTEND=noninteractive;

# Update package repos.

apt-get update --yes; # Update & upgrade all existing.
apt-get upgrade --yes --option 'Dpkg::Options::=--force-confnew';

# Install APT dependencies.

apt-get install ca-certificates --yes;
apt-get install apt-transport-https --yes;
apt-get install software-properties-common --yes;

# Set an english/UTF-8 locale.

apt-get install language-pack-en-base --yes;
export LC_ALL=en_US.UTF-8; export LANG=en_US.UTF-8;

# Add multiverse repo.

apt-add-repository multiverse --yes;
apt-get update; # Update again.
