#!/usr/bin/env bash

if [[ "${CFG_IS_INSTALLER}" == 1 || "${CFG_IS_UPDATER}" == 1 ]]; then

  # Cleanup archives.

  if ! is-vagrant; then
    apt-get clean --yes;
  fi;

  # Remove root SSH key (security).
  # Note that VMs don't generally require an SSH key.
  # If an administrator uploads them though, leave them there.

  if ! is-vagrant; then
    rm --force /root/.ssh/id_rsa;
    rm --force /root/.ssh/ws-bot-np;
    rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/id_rsa;
    rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/ws-bot-np;
  fi;
fi;
