#!/usr/bin/env bash

# Install GPGv2.

apt-get install gnupg2 --yes;
ln --symbolic --force /usr/bin/gpg2 /usr/bin/gpg;

# Install Keybase utility.

mkdir --parents /usr/local/src/keybase;

curl https://dist.keybase.io/linux/deb/keybase-latest-amd64.deb --location \
   --output /usr/local/src/keybase/latest-amd64.deb;

apt-get install libappindicator1 --yes;
dpkg --install /usr/local/src/keybase/latest-amd64.deb;
