#!/usr/bin/env bash

if [[ "${CFG_INSTALL_MAILHOG}" == 1 ]]; then

  # Install MailHog.

  curl https://github.com/mailhog/MailHog/releases/download/v0.2.0/MailHog_linux_amd64 --location --output /usr/bin/mailhog;
  chmod +x /usr/bin/mailhog; # Make it executable.

  # Modify the `sendmail_path` used by PHP.

  echo "sendmail_path = '/usr/bin/mailhog sendmail mailhog@127.0.0.1'" >> /bootstrap/src/php/.ini;

  # Install systemd configuration file.

  cp /bootstrap/src/mailhog/.service /etc/systemd/system/mailhog.service;
  systemctl daemon-reload; # Restart systemd after updating umask.

  # Enable automatic startup.

  systemctl enable mailhog;

  # Maybe create an RUnit startup script.

  maybe-add-runit-service mailhog;

  # Restart service.

  service mailhog restart;

else echo 'Skipping MailHog installation.'; fi;
