#!/usr/bin/env bash

if [[ "${CFG_INSTALL_MEMCACHE}" == 1 ]]; then

  # Install Memcached daemon.

  apt-get install memcached --yes;

  # Config RAM allowance.

  rm --force /etc/memcached.conf;
  ln --symbolic /bootstrap/src/memcache/.conf /etc/memcached.conf;

  # Maybe create an RUnit startup script.

  if in-docker && can-run sv; then
    mkdir --parents /etc/service/memcached;
    ln --symbolic /bootstrap/src/docker/runit/memcached /etc/service/memcached/run;
  fi;
  # Restart service.

  service memcached restart;

else echo 'Skipping Memcache installation.'; fi;
