#!/usr/bin/env bash

if [[ "${CFG_INSTALL_MEMCACHE}" == 1 ]]; then

  # Install Memcached daemon.

  apt-get install memcached --yes;

  # Config RAM allowance.

  rm --force /etc/memcached.conf;
  ln --symbolic /bootstrap/src/memcache/.conf /etc/memcached.conf;

  # Enable automatic startup.

  systemctl enable memcached;

  # Maybe create an RUnit startup script.

  maybe-add-runit-service memcached;

  # Restart service.

  service memcached restart;

else echo 'Skipping Memcache installation.'; fi;
