#!/usr/bin/env bash

if [[ "${CFG_INSTALL_MEMCACHE}" == 1 ]]; then

  # Install Memcached daemon.

  apt-get install memcached --yes;

  # Config RAM allowance.

  rm --force /etc/memcached.conf;
  ln --symbolic /bootstrap/src/memcache/.conf /etc/memcached.conf;

  # Restart service.

  service memcached restart;

else echo 'Skipping Memcache installation.'; fi;
