#!/usr/bin/env bash

# App directories.

mkdir --parents /app;
mkdir --parents /app/src;

if is-vm; then # Use symlink.
  rm --force --recursive /app/src;
  ln --symbolic /bootstrap/app/src /app/src;
fi;
chown --recursive nobody:app /app;
find /app -type d -exec chmod 2775 {} \;
find /app -type f -exec chmod 664 {} \;

# App repo directory for downloads.

mkdir --parents /repos/app.dls;
chown --recursive nobody:app /repos/app.dls;
find /repos/app.dls -type d -exec chmod 2775 {} \;
find /repos/app.dls -type f -exec chmod 664 {} \;

# App repo directory for git deployments.
# See also: `/src/setups/app-repo`.

mkdir --parents /repos/app.git;
chown --recursive nobody:app /repos/app.git;
find /repos/app.git -type d -exec chmod 2775 {} \;
find /repos/app.git -type f -exec chmod 664 {} \;

# App logs directory.

mkdir --parents /var/log/app;
chown --recursive nobody:www-data /var/log/app;
find /var/log/app -type d -exec chmod 2775 {} \;
find /var/log/app -type f -exec chmod 664 {} \;

# Systematics.

mkdir --parents /usr/local/src;
mkdir --parents /etc/bootstrap;

# When packaging, don't rely upon shared folders.

if is-vagrant && is-4pkg; then
  rm --force --recursive /bootstrap;
  cp --force --recursive --preserve=all /vagrant/. /bootstrap;
fi;
