#!/usr/bin/env bash

# When packaging, don't rely upon shared folders.

if is-vagrant && is-4pkg && [[ -d /vagrant && -L /bootstrap ]]; then
  rm /bootstrap; mkdir /bootstrap;
  cp --force --recursive --preserve=all /vagrant/. /bootstrap;
  rm --force --recursive /bootstrap/.vagrant;
fi;
# App web directories.

if is-vm && [[ ! -d /app ]]; then
  ln --symbolic /bootstrap/src/app /app;
fi; # Uses `/bootstrap/src/app` symlink as a fallback.
# On Vagrant, `/app` and `/app/src` should be mounted already.

mkdir --parents /app;
mkdir --parents /app/src;

chown --recursive nobody:app /app;
find /app -type d -exec chmod 2775 {} \;
find /app -type f -exec chmod 664 {} \;

chown --recursive www-data:app /app/src;
find /app/src -type d -exec chmod 2775 {} \;
find /app/src -type f -exec chmod 664 {} \;

# App repo directory for downloads.

mkdir --parents /repos/app.dls;
chown --recursive nobody:app /repos/app.dls;
find /repos/app.dls -type d -exec chmod 2775 {} \;
find /repos/app.dls -type f -exec chmod 664 {} \;

# App repo directory for git deployments.
# See also: `/src/setups/app-repo`.

mkdir --parents /repos/app.git;
chown --recursive nobody:app /repos/app.git;
find /repos/app.git -type d -exec chmod 2775 {} \;
find /repos/app.git -type f -exec chmod 664 {} \;

# App logs directory.

mkdir --parents /var/log/app;
chown --recursive nobody:www-data /var/log/app;
find /var/log/app -type d -exec chmod 2775 {} \;
find /var/log/app -type f -exec chmod 664 {} \;

# Systematics.

mkdir --parents /usr/local/src;
mkdir --parents /etc/bootstrap;
