#!/usr/bin/env bash

if [[ "${CFG_INSTALL_MYSQL}" == 1 ]]; then

  # Install MariaDB (i.e., MySQL).

  mkdir --parents /var/log/mysql;
  chmod 0777 /var/log/mysql;

  apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db;
  add-apt-repository 'deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu trusty main';
  apt-get update; # Update after adding new repo.

  echo 'mariadb-server mysql-server/root_password password '"${CFG_MYSQL_DB_PASSWORD}" | debconf-set-selections;
  echo 'mariadb-server mysql-server/root_password_again password '"${CFG_MYSQL_DB_PASSWORD}" | debconf-set-selections;
  apt-get install mariadb-server --yes; # Install w/ the above options.

  if in-docker && can-run sv; then
    mkdir --parents /etc/service/mysql;
    ln --symbolic /bootstrap/src/docker/runit/mysql /etc/service/mysql/run;
  fi;
  service mysql restart; # Make sure the service is up and running for the following commands.

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'localhost' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}';";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'${CFG_MYSQL_DB_HOST}' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}';";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'%' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}' REQUIRE SSL;";

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="CREATE DATABASE \`${CFG_MYSQL_DB_NAME}\` CHARACTER SET '${CFG_MYSQL_DB_CHARSET}' COLLATE '${CFG_MYSQL_DB_COLLATE}';";

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DELETE FROM \`mysql\`.\`user\` WHERE \`User\` = '';";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DELETE FROM \`mysql\`.\`user\` WHERE \`User\` = 'root' AND \`Host\` NOT IN ('localhost', '127.0.0.1', '::1');";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DROP DATABASE IF EXISTS \`test\`; DELETE FROM \`mysql\`.\`db\` WHERE \`Db\` = 'test' OR \`Db\` LIKE 'test\\_%';";

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="FLUSH PRIVILEGES;";

  ln --symbolic /bootstrap/src/mysql/.cnf /etc/mysql/conf.d/z90.cnf;

  if [[ -f /etc/apparmor.d/local/usr.sbin.mysqld ]]; then
  echo '/bootstrap/src/mysql/.cnf r,' >> /etc/apparmor.d/local/usr.sbin.mysqld; fi;

  # Install phpMyAdmin for MySQL administration.

  git clone https://github.com/phpmyadmin/phpmyadmin /usr/local/src/pma --branch=STABLE --depth=1;
  ln --symbolic /bootstrap/src/tools/.pma.php /usr/local/src/pma/config.inc.php;
  ln --symbolic /usr/local/src/pma /bootstrap/src/tools/pma;

  # Restart service.

  service mysql restart;

  # Import a MySQL database?

  if [[ -f "${CFG_INSTALL_MYSQL_DB_IMPORT_FILE}" ]]; then
    mysql \
      --user="${CFG_MYSQL_DB_USERNAME}" \
      --password="${CFG_MYSQL_DB_PASSWORD}" \
      "${CFG_MYSQL_DB_NAME}" < "${CFG_INSTALL_MYSQL_DB_IMPORT_FILE}";
  fi;

else echo 'Skipping MariaDB (MySQL) installation.'; fi;
