#!/usr/bin/env bash

if [[ "${CFG_INSTALL_MYSQL}" == 1 ]]; then

  # Install MariaDB (i.e., MySQL).

  mkdir --parents /var/log/mysql;
  chmod 0777 /var/log/mysql;

  apt-get install mariadb-server --yes;

  # Enable automatic startup.

  systemctl enable mysql;

  # Maybe create an RUnit startup script.

  maybe-add-runit-service mysql;

  # Make sure the service is up and running for the following commands.

  service mysql restart; # Start MySQL and tighten security.

  mysql --user=root --execute="UPDATE \`mysql\`.\`user\` SET \`password\` = PASSWORD('${CFG_MYSQL_DB_PASSWORD}') WHERE \`user\` = 'root';";

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'localhost' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}';";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'${CFG_MYSQL_DB_HOST}' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}';";

  if is-vm; then # Don't require SSL for external connections to a VM.
    mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'%' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}';";
  else mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="GRANT ALL ON *.* TO '${CFG_MYSQL_DB_USERNAME}'@'%' IDENTIFIED BY '${CFG_MYSQL_DB_PASSWORD}' REQUIRE SSL;"; fi;

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="CREATE DATABASE \`${CFG_MYSQL_DB_NAME}\` CHARACTER SET '${CFG_MYSQL_DB_CHARSET}' COLLATE '${CFG_MYSQL_DB_COLLATE}';";

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DELETE FROM \`mysql\`.\`user\` WHERE \`User\` = '';";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DELETE FROM \`mysql\`.\`user\` WHERE \`User\` = 'root' AND \`Host\` NOT IN ('localhost', '127.0.0.1', '::1');";
  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="DROP DATABASE IF EXISTS \`test\`; DELETE FROM \`mysql\`.\`db\` WHERE \`Db\` = 'test' OR \`Db\` LIKE 'test\\_%';";

  mysql --user=root --password="${CFG_MYSQL_DB_PASSWORD}" --execute="FLUSH PRIVILEGES;";

  ln --symbolic /bootstrap/src/mysql/.cnf /etc/mysql/mariadb.conf.d/z90.cnf;

  if [[ -f /etc/apparmor.d/local/usr.sbin.mysqld ]]; then
  echo '/bootstrap/src/mysql/.cnf r,' >> /etc/apparmor.d/local/usr.sbin.mysqld; fi;

  # Install phpMyAdmin for MySQL administration.

  if ! is-4ci; then # We don't need this in a CI server.
    git clone https://github.com/phpmyadmin/phpmyadmin /usr/local/src/pma --branch=STABLE --depth=1;
    ln --symbolic /bootstrap/src/tools/.pma.php /usr/local/src/pma/config.inc.php;
    ln --symbolic /usr/local/src/pma /bootstrap/src/tools/pma;
  fi;
  # Restart service.

  service mysql restart;

else echo 'Skipping MariaDB (MySQL) installation.'; fi;
