#!/usr/bin/env bash

if [[ "${CFG_INSTALL_NGINX}" == 1 ]]; then

  # Install Ngnix web server.

  apt-add-repository ppa:nginx/development --yes;
  apt-get update; # Update after adding repo.
  apt-get install nginx --yes;

  # Config Ngnix web server.

  rm --force /etc/nginx/nginx.conf;
  rm --force /etc/nginx/sites-enabled/default;

  mkdir --parents /etc/nginx/conf.d/http;
  mkdir --parents /etc/nginx/conf.d/server;
  ln --symbolic /bootstrap/src/nginx/.conf /etc/nginx/nginx.conf;

  if is-vm; then # Disable sendfile on VMs.
    perl -i -wpe 's/^(\s*)sendfile\s+.*$/$1sendfile off;/u' /bootstrap/src/nginx/.conf;
  fi; # See: <https://docs.vagrantup.com/v2/synced-folders/virtualbox.html>

  perl -i -0wpe 's/%%cookie_maintenance_bypass_value%%/'"${CFG_MAINTENANCE_BYPASS_KEY}"'/ug' /bootstrap/src/nginx/.conf;

  if [[ "${CFG_FIREWALL_ALLOWS_CF_ONLY_VIA_80_443}" == 1 ]]; then
    # See: <https://www.cloudflare.com/ips/>
    _ips_v4="$(curl https://www.cloudflare.com/ips-v4 --location)";
    _ips_v6="$(curl https://www.cloudflare.com/ips-v6 --location)";

    : > /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf;

    while read -ra _ip; do
      _ip="$(trim "${_ip}")";
      if [[ -n "${_ip}" ]]; then
        echo 'set_real_ip_from '"${_ip}"';' >> /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf;
      fi;
    done <<< "${_ips_v4}"$'\n'"${_ips_v6}"; unset _ips_v4; unset _ips_v6; unset _ip;
    echo 'real_ip_header cf-connecting-ip;' >> /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf;

    ln --symbolic /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf /etc/nginx/conf.d/server/cf-real-ip.conf;
  fi;
  # Maybe create an RUnit startup script.

  maybe-add-runit-service nginx;

  # Put live sites into maintenance mode by default.

  if ! is-vm; then
    touch /app/.maintenance; fi;

  # Restart service.

  service nginx restart;

else echo 'Skipping Nginx installation.'; fi;
