#!/usr/bin/env bash

if [[ "${CFG_INSTALL_NGINX}" == 1 ]]; then

  # Install Ngnix web server.

  apt-add-repository ppa:nginx/development --yes;
  apt-get update; # Update after adding repo.
  apt-get install nginx --yes;

  # Config Ngnix web server.

  rm --force /etc/nginx/nginx.conf;
  rm --force /etc/nginx/sites-enabled/default;

  mkdir --parents /etc/nginx/conf.d/main;
  mkdir --parents /etc/nginx/conf.d/http;
  mkdir --parents /etc/nginx/conf.d/server;
  mkdir --parents /var/nginx/proxy-cache;

  ln --symbolic /bootstrap/src/nginx/.conf /etc/nginx/nginx.conf;
  cat /etc/nginx/~env.conf >> /etc/nginx/env.conf; rm /etc/nginx/~env.conf;

  ln --symbolic /bootstrap/src/nginx/conf.d/main/_defaults.conf /etc/nginx/conf.d/main/_defaults.conf;
  ln --symbolic /bootstrap/src/nginx/conf.d/http/_defaults.conf /etc/nginx/conf.d/http/_defaults.conf;
  ln --symbolic /bootstrap/src/nginx/conf.d/server/_defaults.conf /etc/nginx/conf.d/server/_defaults.conf;

  # WordPress multisite network support. Not enabled by default; just for reference.
  #ln --symbolic /bootstrap/src/nginx/conf.d/server/wp-ms.conf /etc/nginx/conf.d/server/wp-ms.conf;

  if is-vm; then # Disable sendfile on VMs.
    perl -i -wpe 's/^(\s*)sendfile\s+.*$/$1sendfile off;/u' /bootstrap/src/nginx/snippets/http/_defaults/general.conf;
  fi; # See: <https://docs.vagrantup.com/v2/synced-folders/virtualbox.html>

  if is-vm; then # Disable HSTS on VMs so that `http://` tools like MailHog will work.
    perl -i -wpe 's/^(\s*)(add_header\s+strict\-transport\-security\s+.*)$/$1#$2/ui' /bootstrap/src/nginx/snippets/http/_defaults/hsts.conf;
  fi; # See: <http://classically.me/blogs/how-clear-hsts-settings-major-browsers>

  if [[ "${CFG_FIREWALL_ALLOWS_CF_ONLY_VIA_80_443}" == 1 ]]; then
    # See: <https://www.cloudflare.com/ips/>
    _ips_v4="$(curl https://www.cloudflare.com/ips-v4 --location)";
    _ips_v6="$(curl https://www.cloudflare.com/ips-v6 --location)";

    : > /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf;

    while read -ra _ip; do
      _ip="$(trim "${_ip}")";
      if [[ -n "${_ip}" ]]; then
        echo 'set_real_ip_from '"${_ip}"';' >> /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf;
      fi;
    done <<< "${_ips_v4}"$'\n'"${_ips_v6}"; unset _ips_v4; unset _ips_v6; unset _ip;
    echo 'real_ip_header cf-connecting-ip;' >> /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf;

    ln --symbolic /bootstrap/src/nginx/conf.d/server/cf-real-ip.conf /etc/nginx/conf.d/server/cf-real-ip.conf;
  fi;
  # Bug fix. See: <https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864>

  mkdir --parents /etc/systemd/system/nginx.service.d;
  echo '[Service]' >> /etc/systemd/system/nginx.service.d/override.conf;
  echo 'ExecStartPost=/bin/sleep 0.1' >> /etc/systemd/system/nginx.service.d/override.conf;
  systemctl daemon-reload; # Restart systemd.

  # Enable automatic startup.

  systemctl enable nginx;

  # Maybe create an RUnit startup script.

  maybe-add-runit-service nginx;

  # Put live sites into maintenance mode.

  if ! is-vm; then
    touch /app/.maintenance; fi;

  # Restart service.

  service nginx restart;

else echo 'Skipping Nginx installation.'; fi;
