#!/usr/bin/env bash

if [[ "${CFG_INSTALL_OPENVPN}" == 1 ]]; then

  # Install OpenVPN.

  apt-get install openvpn --yes;

  # Configure OpenVPN.
  # See: <http://jas.xyz/2cuqxDM>

  mkdir --parents /var/log/openvpn;
  mkdir --parents /etc/bootstrap/openvpn;

  openvpn --genkey --secret /etc/bootstrap/openvpn/tls-auth.key;
  ln --symbolic /bootstrap/src/openvpn/.conf /etc/openvpn/server.conf;

  if is-do && do-has-floating-ip; then
    perl -i -wpe 's/^%%local%%$/local '"$(esc-regex-rv "$(do-anchor-ip)")"'/u' /etc/openvpn/server.conf;
  else perl -i -0wpe 's/\n%%local%%\n/\n/u' /etc/openvpn/server.conf; fi;

  # Build client configuration file.

  ln --symbolic /bootstrap/src/openvpn/.ovpn /etc/bootstrap/openvpn/client.ovpn;

  if is-do && do-has-floating-ip; then
    perl -i -0wpe 's/%%remote%%/'"$(esc-regex-rv "$(do-floating-ip)")"'/ug' /etc/bootstrap/openvpn/client.ovpn;
  else perl -i -0wpe 's/%%remote%%/'"$(esc-regex-rv "${CFG_HOST}")"'/ug' /etc/bootstrap/openvpn/client.ovpn; fi;

  perl -i -0wpe 's/%%host%%/'"$(esc-regex-rv "${CFG_HOST}")"'/ug' /etc/bootstrap/openvpn/client.ovpn;

  echo $'\n''# Certificate files (inline).'$'\n' >> /etc/bootstrap/openvpn/client.ovpn;

  echo '<ca>' >> /etc/bootstrap/openvpn/client.ovpn; # Server CA certificate.
  cat /etc/bootstrap/ssl/server-ca-crt.pem >> /etc/bootstrap/openvpn/client.ovpn;
  echo '</ca>'$'\n' >> /etc/bootstrap/openvpn/client.ovpn;

  echo '<cert>' >> /etc/bootstrap/openvpn/client.ovpn; # Client certificate.
  cat /etc/bootstrap/ssl/client-crt.pem >> /etc/bootstrap/openvpn/client.ovpn;
  echo '</cert>'$'\n' >> /etc/bootstrap/openvpn/client.ovpn;

  echo '<key>' >> /etc/bootstrap/openvpn/client.ovpn; # Client private key.
  cat /etc/bootstrap/ssl/client-private-key.pem >> /etc/bootstrap/openvpn/client.ovpn;
  echo '</key>'$'\n' >> /etc/bootstrap/openvpn/client.ovpn;

  echo '<tls-auth>' >> /etc/bootstrap/openvpn/client.ovpn; # TLS auth key.
  cat /etc/bootstrap/openvpn/tls-auth.key >> /etc/bootstrap/openvpn/client.ovpn;
  echo '</tls-auth>' >> /etc/bootstrap/openvpn/client.ovpn;

  # Email details for easy client setup.

  if can-run mail; then # Only if it's possible.
    cp /etc/bootstrap/openvpn/client.ovpn /tmp/"${CFG_HOST}".ovpn;

    mail --subject='OpenVPN Client Setup' --attach=/tmp/"${CFG_HOST}".ovpn \
      "${CFG_ADMIN_EMAIL}" <<< 'Configuration file for OpenVPN @'"${CFG_HOST}";

    rm /tmp/"${CFG_HOST}".ovpn; # Remove temporary file now.
  fi;
  # Enable automatic startup.

  systemctl enable openvpn@server;

  # Add extra startup specs for better compatibility.
  # i.e., Compatibility with the `local` directive for OpenVPN.
  # The `local` directive requires networking dependency so it can bind correctly.

  mkdir /etc/systemd/system/openvpn@.service.d;
  echo '[Unit]' >> /etc/systemd/system/openvpn@.service.d/override.conf;
  echo 'Requires=networking.service' >> /etc/systemd/system/openvpn@.service.d/override.conf;
  echo 'After=networking.service' >> /etc/systemd/system/openvpn@.service.d/override.conf;

  # Restart service.

  service openvpn@server restart;

else echo 'Skipping OpenVPN installation.'; fi;
