#!/usr/bin/env bash

if can-run php && [[ "${CFG_INSTALL_PHING}" == 1 ]]; then

  # Install Phing for PHP.

  curl http://www.phing.info/get/phing-latest.phar --location --output /usr/bin/phing;
  chmod +x /usr/bin/phing; # Make it executable.

else echo 'Skipping Phing installation.'; fi;
