#!/usr/bin/env bash

if [[ "${CFG_INSTALL_PMA}" == 1 ]]; then

  # Install phpMyAdmin for MySQL administration.

  git clone https://github.com/phpmyadmin/phpmyadmin /usr/local/src/pma --branch=STABLE --depth=1;

  ln --symbolic /bootstrap/src/tools/.pma.php /usr/local/src/pma/config.inc.php;
  ln --symbolic /usr/local/src/pma /bootstrap/src/tools/pma;

  cd /usr/local/src/pma;
  composer install;

else echo 'Skipping PMA installation.'; fi;
