#!/usr/bin/env bash

if [[ "${CFG_INSTALL_POSTFIX}" == 1 ]]; then

  # Install Postfix; see: <https://help.ubuntu.com/community/Postfix>

  echo 'postfix postfix/main_mailer_type string "Internet Site"' | debconf-set-selections;
  echo 'postfix postfix/mailname string '"$(hostname --long)" | debconf-set-selections;
  apt-get install postfix --yes; # Install w/ the above options.

  # Tweak the main config file.
  # We do NOT open port 25, so TLS can be disabled here.
  # We disable TLS, because it's not worth configuring the certificate files.
  perl -i -wpe 's/^(\s*)smtpd_use_tls\s\=.*$/$1smtpd_use_tls=no/u' /etc/postfix/main.cf;

  # Restart service.

  service postfix restart;

  # Install mail utilities.

  apt-get install mailutils --yes;

else echo 'Skipping Postfix installation.'; fi;
