#!/usr/bin/env bash

if in-docker && can-run sv; then

  # Configure RUnit.

  ## Create service dir.

  mkdir --parents /etc/service;

  ## Create an Upstart `service` alias.

  mv /usr/sbin/service /usr/sbin/service~;
  ln --symbolic /bootstrap/src/bin/runit-service /usr/sbin/service;

fi;
