#!/usr/bin/env bash

# Maybe harden SSH security.

if ! is-vm; then # On production servers only.

  perl -i -wpe 's/^(\s*)PermitRootLogin\s+.*$/$1PermitRootLogin no/ui' /etc/ssh/sshd_config;
  echo '# Allow Specific Groups Only' >> /etc/ssh/sshd_config;
  echo 'AllowGroups sudo ssh-access' >> /etc/ssh/sshd_config;

  echo '# SFTP Only Group Restrictions' >> /etc/ssh/sshd_config;
  echo 'Match Group sftp-only' >> /etc/ssh/sshd_config;
  echo '    AllowTCPForwarding no' >> /etc/ssh/sshd_config;
  echo '    X11Forwarding no' >> /etc/ssh/sshd_config;
  echo '    ForceCommand internal-sftp' >> /etc/ssh/sshd_config;

  perl -i -wpe 's/^(\s*)Subsystem\s+sftp\s+.*$/$1Subsystem sftp internal-sftp/ui' /etc/ssh/sshd_config;

  service ssh restart;

else echo 'Skipping SSH configuration & security hardening.'; fi;
