#!/usr/bin/env bash

if [[ "${CFG_INSTALL_SWAP}" == 1 ]]; then

  # Configure swap space.
  # see <http://jas.xyz/1NFX0iw>

  if ! fallocate -l 4G /swap; then
    dd if=/dev/zero of=/swap bs=1024 count=$[1024*4000];
  fi; # Fallback on `dd`. See: <http://jas.xyz/25y9SCQ>

  chmod 600 /swap;
  mkswap /swap; swapon /swap;
  echo '/swap none swap sw 0 0' >> /etc/fstab;

  echo '10' > /proc/sys/vm/swappiness;
  echo 'vm.swappiness = 10' >> /etc/sysctl.conf;

  sysctl vm.vfs_cache_pressure=50;
  echo 'vm.vfs_cache_pressure = 50' >> /etc/sysctl.conf;

else echo 'Skipping /swap installation.'; fi;
