#!/usr/bin/env bash

# New groups.

addgroup app;
addgroup ssh-access;
addgroup sftp-only;

# Create & setup admin.

create-admin \
  --user="${CFG_ADMIN_USERNAME}" \
  --pass="${CFG_ADMIN_PASSWORD}";

setup-admin \
  --user="${CFG_ADMIN_USERNAME}" \
  --name="${CFG_ADMIN_NAME}" \
  --email="${CFG_ADMIN_EMAIL}" \
  --shell="${CFG_ADMIN_PREFERRED_SHELL}" \
  --ssh-keys="${CFG_ADMIN_AUTHORIZED_SSH_KEYS}";

# Maybe setup vagrant admin.

if is-vagrant; then

  setup-admin \
    --user=vagrant \
    --name="${CFG_ADMIN_NAME}" \
    --email="${CFG_ADMIN_EMAIL}" \
    --shell="${CFG_ADMIN_PREFERRED_SHELL}";

  # In case `/etc/sudoers` is modified by initial `upgrade`.
  echo 'vagrant ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant;

fi;
# Setup root admin.

setup-admin \
  --user=root \
  --name="${CFG_ADMIN_NAME}" \
  --email="${CFG_ADMIN_EMAIL}" \
  --shell="${CFG_ADMIN_PREFERRED_SHELL}";

# Authentication for web-based tools.

mkdir --parents /etc/bootstrap/passwds;
htpasswd -cb /etc/bootstrap/passwds/.tools "${CFG_TOOLS_USERNAME}" "${CFG_TOOLS_PASSWORD}";
