#!/usr/bin/env bash

# New groups.

addgroup app;
addgroup ssh-access;
addgroup sftp-only;

# Create admin user.

create-user \
  --user="${CFG_ADMIN_USERNAME}" \
  --pass="${CFG_ADMIN_PASSWORD}";

setup-user \
  --user="${CFG_ADMIN_USERNAME}" \
  --name="${CFG_ADMIN_NAME}" \
  --email="${CFG_ADMIN_EMAIL}" \
  --shell="${CFG_ADMIN_PREFERRED_SHELL}" \
  --ssh-keys="${CFG_ADMIN_AUTHORIZED_SSH_KEYS}";

usermod --append --groups=adm "${CFG_ADMIN_USERNAME}";
usermod --append --groups=app "${CFG_ADMIN_USERNAME}";
usermod --append --groups=sudo "${CFG_ADMIN_USERNAME}";
usermod --append --groups=ssh-access "${CFG_ADMIN_USERNAME}";
usermod --append --groups=www-data "${CFG_ADMIN_USERNAME}";

# If running a VM, setup the vagrant user.

if is-vagrant; then

  setup-user \
    --user=vagrant \
    --name="${CFG_ADMIN_NAME}" \
    --email="${CFG_ADMIN_EMAIL}" \
    --shell="${CFG_ADMIN_PREFERRED_SHELL}";

  usermod --append --groups=adm vagrant;
  usermod --append --groups=app vagrant;
  usermod --append --groups=sudo vagrant;
  usermod --append --groups=ssh-access vagrant;
  usermod --append --groups=www-data vagrant;

fi; # On vagrant boxes only.

# Setup the root user also.

setup-user \
  --user=root \
  --name="${CFG_ADMIN_NAME}" \
  --email="${CFG_ADMIN_EMAIL}" \
  --shell="${CFG_ADMIN_PREFERRED_SHELL}";
