#!/usr/bin/env bash

# New groups.

addgroup app;
addgroup ssh-access;
addgroup sftp-only;

# Setup root admin.

setup-admin \
  --user=root \
  --name="${CFG_ADMIN_NAME}" \
  --email="${CFG_ADMIN_EMAIL}" \
  --shell="${CFG_ADMIN_PREFERRED_SHELL}" \
  --ssh-keys="${CFG_ADMIN_AUTHORIZED_SSH_KEYS}" \
  --static-ip="${CFG_ADMIN_STATIC_IP_ADDRESS}";

# Maybe setup system admins.

if is-vagrant && user-exists ubuntu; then

  setup-admin \
    --user=ubuntu \
    --name="${CFG_ADMIN_NAME}" \
    --email="${CFG_ADMIN_EMAIL}" \
    --shell="${CFG_ADMIN_PREFERRED_SHELL}" \
    --ssh-keys="${CFG_ADMIN_AUTHORIZED_SSH_KEYS}" \
    --static-ip="${CFG_ADMIN_STATIC_IP_ADDRESS}";

  # In case `/etc/sudoers` is modified by initial `upgrade`.
  echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu;
fi;

if is-vagrant && user-exists vagrant; then

  setup-admin \
    --user=vagrant \
    --name="${CFG_ADMIN_NAME}" \
    --email="${CFG_ADMIN_EMAIL}" \
    --shell="${CFG_ADMIN_PREFERRED_SHELL}" \
    --ssh-keys="${CFG_ADMIN_AUTHORIZED_SSH_KEYS}" \
    --static-ip="${CFG_ADMIN_STATIC_IP_ADDRESS}";

  # In case `/etc/sudoers` is modified by initial `upgrade`.
  echo 'vagrant ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant;
fi;

# Create & setup 'the' admin.

create-admin \
  --user="${CFG_ADMIN_USERNAME}" \
  --pass="${CFG_ADMIN_PASSWORD}";

setup-admin \
  --user="${CFG_ADMIN_USERNAME}" \
  --name="${CFG_ADMIN_NAME}" \
  --email="${CFG_ADMIN_EMAIL}" \
  --shell="${CFG_ADMIN_PREFERRED_SHELL}" \
  --ssh-keys="${CFG_ADMIN_AUTHORIZED_SSH_KEYS}" \
  --static-ip="${CFG_ADMIN_STATIC_IP_ADDRESS}";
