#!/usr/bin/env bash

if [[ "${CFG_INSTALL_WEBSHARKS_CORE}" == 1 ]]; then

  # Install websharks/core library.

  git clone https://github.com/websharks/core /usr/local/src/websharks-core --branch=master --depth=1;

  # Satisfy websharks/core dependencies.

  cd /usr/local/src/websharks-core;
  git submodule update --recursive --force --init;
  phing post-receive-build;

  # Configure websharks/core CRON jobs.

  echo '@hourly root /bootstrap/src/crons/logs-via-email >/dev/null 2>&1' >> /etc/crontab;

else echo 'Skipping websharks/core installation'; fi;
