#!/usr/bin/env bash

# When adding a new version:
# - Update: `Vagrantfile` (add sub-domain variation).
# - Update: `.box.Vagrantfile` (add sub-domain variation).
# - Update: `/bootstrap/src/bash/app-related-services` (add service).
# - Update: `/bootstrap/src/wordpress/dev/README.md` (adjust as necessary).
# - CloudFlare DNS records should be added for all team members.

if [[ "${CFG_INSTALL_WORDPRESS_DEV_CONTAINERS}" == 1 ]]; then

  # Install WordPress dev containers.
  # <https://hub.docker.com/r/chialab/php/tags/>

  /bootstrap/src/wordpress/install-dev 5.4;
  /bootstrap/src/wordpress/install-dev 5.5;
  /bootstrap/src/wordpress/install-dev 5.6;
  /bootstrap/src/wordpress/install-dev 7.0;
  /bootstrap/src/wordpress/install-dev 7.1;

  # If this is for another user, create that user now.

  if [[ -n "${CFG_WORDPRESS_DEV_USERNAME}" && -n "${CFG_WORDPRESS_DEV_PASSWORD}" ]]; then
    if ! user-exists "${CFG_WORDPRESS_DEV_USERNAME}"; then
      create-admin \
        --user="${CFG_WORDPRESS_DEV_USERNAME}" \
        --pass="${CFG_WORDPRESS_DEV_PASSWORD}";

      setup-admin \
        --user="${CFG_WORDPRESS_DEV_USERNAME}" \
        --name="${CFG_WORDPRESS_DEV_NAME}" \
        --email="${CFG_WORDPRESS_DEV_EMAIL}" \
        --shell="${CFG_WORDPRESS_DEV_PREFERRED_SHELL}" \
        --static-ip="${CFG_WORDPRESS_DEV_STATIC_IP_ADDRESS}" \
        --ssh-keys="${CFG_WORDPRESS_DEV_AUTHORIZED_SSH_KEYS}";
    fi;
    if is-dev && is-do && [[ -n "${CFG_WORDPRESS_DEV_STATIC_IP_ADDRESS}" ]] && can-run mail; then
      cp /bootstrap/src/wordpress/dev/README.md /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%do_region%%/'"$(esc-regex-rv "$(do-region)")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_WORDPRESS_DEV_STATIC_IP_ADDRESS%%/'"$(esc-regex-rv "${CFG_WORDPRESS_DEV_STATIC_IP_ADDRESS}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_WORDPRESS_DEV_USERNAME%%/'"$(esc-regex-rv "${CFG_WORDPRESS_DEV_USERNAME}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_WORDPRESS_DEV_PASSWORD%%/'"$(esc-regex-rv "${CFG_WORDPRESS_DEV_PASSWORD}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_HOST%%/'"$(esc-regex-rv "${CFG_HOST}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MAINTENANCE_BYPASS_KEY%%/'"$(esc-regex-rv "${CFG_MAINTENANCE_BYPASS_KEY}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_INSTALL_PHP_VERSION%%/'"$(esc-regex-rv "${CFG_INSTALL_PHP_VERSION}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_DB_HOST%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_HOST}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MYSQL_DB_PORT%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_PORT}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_DB_NAME%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_NAME}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_DB_USERNAME%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_USERNAME}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MYSQL_DB_PASSWORD%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_PASSWORD}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_X_DB_USERNAME%%/'"$(esc-regex-rv "${CFG_MYSQL_X_DB_USERNAME}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MYSQL_X_DB_PASSWORD%%/'"$(esc-regex-rv "${CFG_MYSQL_X_DB_PASSWORD}")"'/ug' /tmp/"${CFG_HOST}".md;

      mail --subject='WordPress Dev Instructions' --attach=/tmp/"${CFG_HOST}".md \
        "${CFG_ADMIN_EMAIL}" <<< 'Instructions for WordPress dev @'"${CFG_HOST}";

        rm /tmp/"${CFG_HOST}".md; # Remove temporary file now.
    fi;
  fi;

else echo 'Skipping WordPress dev containers.'; fi;
