#!/usr/bin/env bash

if can-run php && [[ "${CFG_INSTALL_WORDPRESS}" == 1 ]]; then

  # Remove existing `/app`.

  if is-vm && [[ -L /app ]]; then
    rm --force --recursive /bootstrap/src/app/*;
  else rm --force --recursive /app/*; mkdir --parents /app/src; fi;

  # Clone the WordPress master branch.

  curl http://wordpress.org/latest.zip --location --output /tmp/wordpress-latest.zip;
  unzip -qq -d /tmp/wordpress-latest /tmp/wordpress-latest.zip;
  cp --force --recursive --preserve=all /tmp/wordpress-latest/wordpress/. /app/src;

  rm --force --recursive /tmp/wordpress-latest;
  rm /tmp/wordpress-latest.zip;

  # Setup the `/wp-config.php` file on VMs for quick access.

  if is-vm; then # Only for VMs.
    ln --symbolic /bootstrap/src/wordpress/.wp-config.php /app/src/wp-config.php;
    perl -i -wpe 's/%%AUTH_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%SECURE_AUTH_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%LOGGED_IN_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%NONCE_KEY%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%AUTH_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%SECURE_AUTH_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%LOGGED_IN_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
    perl -i -wpe 's/%%NONCE_SALT%%/'"$(esc-regex-rv "$(keygen 64)")"'/u' /bootstrap/src/wordpress/.wp-config.php;
  fi;
  # Set permissions in the `/app` directory.

  chown --recursive nobody:app /app;
  find /app -type d -exec chmod 2775 {} \;
  find /app -type f -exec chmod 664 {} \;

  chown --recursive www-data /app/src;
  find /app/src -type d -exec chmod 2775 {} \;
  find /app/src -type f -exec chmod 664 {} \;

  # Build symlinks to development files when run via Vagrant.
  # Note: These are read-only mounts; to avoid inadvertent changes.

  if [[ "${CFG_INSTALL_WORDPRESS_VM_SYMLINKS}" == 1 ]]; then

    # Create theme/plugin symlinks if possible.

    for _wp_dir in /wordpress /wp-personal /wp-business; do

    	# Create theme symlinks if possible.

    	if [[ -d "${_wp_dir}"/themes ]]; then
    		for _dir in "${_wp_dir}"/themes/*; do
    			rm --force /app/src/wp-content/themes/"$(basename "${_dir}")";

    			if [[ -d "${_dir}"/"$(basename "${_dir}")" ]]; then
    				ln --symbolic --no-target-directory "${_dir}"/"$(basename "${_dir}")" /app/src/wp-content/themes/"$(basename "${_dir}")";
    			elif [[ -d "${_dir}" ]]; then # Not in a nested sub-directory; i.e., this is the theme directory?
    				ln --symbolic --no-target-directory "${_dir}" /app/src/wp-content/themes/"$(basename "${_dir}")";
    			fi;
    		done; unset _dir;
    	fi;
    	# Create plugin symlinks if possible.

    	if [[ -d "${_wp_dir}"/plugins ]]; then
    		for _dir in "${_wp_dir}"/plugins/*; do
    			rm --force /app/src/wp-content/plugins/"$(basename "${_dir}")";

    			if [[ -d "${_dir}"/"$(basename "${_dir}")" ]]; then
    				ln --symbolic --no-target-directory "${_dir}"/"$(basename "${_dir}")" /app/src/wp-content/plugins/"$(basename "${_dir}")";
    			elif [[ -d "${_dir}" ]]; then # Not in a nested sub-directory; i.e., this is the plugin directory?
    				ln --symbolic --no-target-directory "${_dir}" /app/src/wp-content/plugins/"$(basename "${_dir}")";
    			fi;
    		done; unset _dir;
    	fi;

    done; unset _wp_dir; # End WordPress symlinks.

  else echo 'Skipping WP symlinks.'; fi;

else echo 'Skipping WordPress installation.'; fi;
