#!/usr/bin/env bash

if can-run php && [[ "${CFG_INSTALL_WORDPRESS}" == 1 ]]; then

  # Install WordPress.

  /bootstrap/src/wordpress/install;

  # Maybe install WordPress symlinks.

  if [[ "${CFG_INSTALL_WORDPRESS_VM_SYMLINKS}" == 1 ]]; then
    /bootstrap/src/wordpress/install-symlinks;
  else echo 'Skipping WP symlinks.'; fi;

else echo 'Skipping WordPress installation.'; fi;
