#!/usr/bin/env bash

if can-run docker && [[ "${CFG_INSTALL_WORDPRESS_DEV_CONTAINERS}" == 1 ]]; then

  # Install WordPress dev containers.

  /bootstrap/src/wordpress/install-dev 5.4;
  /bootstrap/src/wordpress/install-dev 5.5;
  /bootstrap/src/wordpress/install-dev 5.6;
  /bootstrap/src/wordpress/install-dev 7.0;

  # /bootstrap/src/wordpress/install-dev 7.1;
  # Unfortunately, a PHP 7.1 container is unavailable.
  # See: <https://hub.docker.com/r/chialab/php/tags/>
  # The checklist below is complete. Just need container.

  # When adding a new version, the following updates must occur.
  # - Update `Vagrantfile` and `.box.Vagrantfile`.
  # - Update `/bootstrap/src/wordpress/dev/README.md`.
  # - Update `/bootstrap/src/bash/app-related-services`.
  # CloudFlare DNS records should be added for all team members.

  # If this is for another user, create that user now.

  if [[ -n "${CFG_WORDPRESS_DEV_USERNAME}" && "${CFG_WORDPRESS_DEV_PASSWORD}" ]]; then
    if ! user-exists "${CFG_WORDPRESS_DEV_USERNAME}"; then
      create-admin \
        --user="${CFG_WORDPRESS_DEV_USERNAME}" \
        --pass="${CFG_WORDPRESS_DEV_PASSWORD}";

      setup-admin \
        --user="${CFG_WORDPRESS_DEV_USERNAME}" \
        --name="${CFG_WORDPRESS_DEV_NAME}" \
        --email="${CFG_WORDPRESS_DEV_EMAIL}" \
        --shell="${CFG_WORDPRESS_DEV_PREFERRED_SHELL}" \
        --ssh-keys="${CFG_WORDPRESS_DEV_AUTHORIZED_SSH_KEYS}";
    fi;
    if is-dev && is-do && do-has-floating-ip && can-run mail; then
      cp /bootstrap/src/wordpress/dev/README.md /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%do_floating_ip%%/'"$(esc-regex-rv "$(do-floating-ip)")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%do_region%%/'"$(esc-regex-rv "$(do-region)")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_WORDPRESS_DEV_USERNAME%%/'"$(esc-regex-rv "${CFG_WORDPRESS_DEV_USERNAME}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_WORDPRESS_DEV_PASSWORD%%/'"$(esc-regex-rv "${CFG_WORDPRESS_DEV_PASSWORD}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_HOST%%/'"$(esc-regex-rv "${CFG_HOST}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MAINTENANCE_BYPASS_KEY%%/'"$(esc-regex-rv "${CFG_MAINTENANCE_BYPASS_KEY}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_INSTALL_PHP_VERSION%%/'"$(esc-regex-rv "${CFG_INSTALL_PHP_VERSION}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_DB_HOST%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_HOST}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MYSQL_DB_PORT%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_PORT}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_DB_NAME%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_NAME}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_DB_USERNAME%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_USERNAME}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MYSQL_DB_PASSWORD%%/'"$(esc-regex-rv "${CFG_MYSQL_DB_PASSWORD}")"'/ug' /tmp/"${CFG_HOST}".md;

      perl -i -0wpe 's/%%CFG_MYSQL_X_DB_USERNAME%%/'"$(esc-regex-rv "${CFG_MYSQL_X_DB_USERNAME}")"'/ug' /tmp/"${CFG_HOST}".md;
      perl -i -0wpe 's/%%CFG_MYSQL_X_DB_PASSWORD%%/'"$(esc-regex-rv "${CFG_MYSQL_X_DB_PASSWORD}")"'/ug' /tmp/"${CFG_HOST}".md;

      mail --subject='WordPress Dev Instructions' --attach=/tmp/"${CFG_HOST}".md \
        "${CFG_ADMIN_EMAIL}" <<< 'Instructions for WordPress dev @'"${CFG_HOST}";

        rm /tmp/"${CFG_HOST}".md; # Remove temporary file now.
    fi;
  fi;

else echo 'Skipping WordPress dev containers.'; fi;
