#!/usr/bin/env bash

if can-run php && [[ "${CFG_INSTALL_WP_CLI}" == 1 ]]; then

  # Install WP-CLI now also.

  curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar --location --output /usr/bin/wp;
  chmod +x /usr/bin/wp; # Make it executable.

else echo 'Skipping WP CLI installation.'; fi;
