#!/usr/bin/env bash

if can-run php && can-run phing && version-compare "$(php -r 'echo PHP_VERSION;')" ge 7.0; then

  # Install websharks/core library.

  git clone https://github.com/websharks/core /usr/local/src/wsc --branch=master --depth=1;

  # Satisfy websharks/core dependencies.

  cd /usr/local/src/wsc;
  git submodule update --recursive --force --init;
  phing post-receive-build;

  # Configure websharks/core CRON jobs.

  echo '@hourly root /bootstrap/src/crons/logs-via-email >/dev/null 2>&1' >> /etc/crontab;

else echo 'Skipping websharks/core installation'; fi;
