#!/usr/bin/env bash

# Zsh installation.

apt-get install zsh --yes;

git clone https://github.com/zsh-users/zsh-completions /usr/local/src/zsh-completions --branch=master --depth=1;
git clone https://github.com/seebi/dircolors-solarized /usr/local/src/dircolors-solarized --branch=master --depth=1;
git clone https://github.com/zsh-users/zsh-syntax-highlighting /usr/local/src/zsh-syntax-highlighting --branch=master --depth=1;
