#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Read PHP version.

php_version="${1:-}";
if [[ -z "${php_version}" ]]; then
  echo 'Expecting PHP version string.'; exit 1;
fi; # Bail on failure to acquire.

# Configuration of the CI server.

container_name_tag=websharks-ubuntu-ci-php"${php_version}"-"$(date +%Y%m%d)";
image_name_tag=websharks/ubuntu-ci-php"${php_version}":"$(date +%Y%m%d)";

# Prepare a new container for this CI image.

docker run --hostname=ci.vm --name="${container_name_tag}" --volume=/bootstrap:/docker phusion/baseimage:0.9.18 \
  /sbin/my_init -- /bootstrap/src/docker/4ci/installer "${php_version}";

# Commit changes to this image and give them a name.

docker commit --change='CMD ["/sbin/my_init"]' \
  --message="${image_name_tag}" --author='WS Ubuntu Bootstrap' \
  "${container_name_tag}" "${image_name_tag}";

# Output details associated with this new image.

echo 'Docker Container: '"${container_name_tag}";
echo 'Docker Image: '"${image_name_tag}";
