#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Read PHP version.

php_version="${1:-}";
if [[ -z "${php_version}" ]]; then
  echo 'Expecting PHP version string.'; exit 1;
fi; # Bail on failure to acquire.

# Bootstrap the CI server.

apt-get update --yes; apt-get install git --yes;
git clone https://github.com/websharks/ubuntu-bootstrap /bootstrap --branch=master --depth=1;
/bootstrap/src/installer --CFG_USE_WIZARD=0 --CFG_4CI=1 --CFG_INSTALL_PHP_VERSION="${php_version}";
