#!/usr/bin/env bash

# Define app-related services.

declare -A ___app_related_services;
declare -a ___app_related_services_order;

# Listed in restart order; stopped in reverse order.
# - `___app_related_services`: Array keys are binaries; values are service names.
# - `___app_related_services_order`: Array values are references to the 'binary' service key.

___app_related_services[ufw]=ufw; ___app_related_services_order+=('ufw');
___app_related_services[fail2ban-client]=fail2ban; ___app_related_services_order+=('fail2ban-client');

___app_related_services[ssh]=ssh; ___app_related_services_order+=('ssh');
___app_related_services[openvpn]=openvpn@server; ___app_related_services_order+=('openvpn');

___app_related_services[postfix]=postfix; ___app_related_services_order+=('postfix');
___app_related_services[mailhog]=mailhog; ___app_related_services_order+=('mailhog');

___app_related_services[docker]=docker; ___app_related_services_order+=('docker');
___app_related_services[docker-app-dev-php5.4]=docker-app-dev-php5.4; ___app_related_services_order+=('docker-app-dev-php5.4');
___app_related_services[docker-app-dev-php5.5]=docker-app-dev-php5.5; ___app_related_services_order+=('docker-app-dev-php5.5');
___app_related_services[docker-app-dev-php5.6]=docker-app-dev-php5.6; ___app_related_services_order+=('docker-app-dev-php5.6');
___app_related_services[docker-app-dev-php7.0]=docker-app-dev-php7.0; ___app_related_services_order+=('docker-app-dev-php7.0');
___app_related_services[docker-app-dev-php7.1]=docker-app-dev-php7.1; ___app_related_services_order+=('docker-app-dev-php7.1');

___app_related_services[discourse]=discourse; ___app_related_services_order+=('discourse');

___app_related_services[memcached]=memcached; ___app_related_services_order+=('memcached');

___app_related_services[mysql]=mysql; ___app_related_services_order+=('mysql');

___app_related_services[php5.5-fpm]=php5.5-fpm; ___app_related_services_order+=('php5.5-fpm');
___app_related_services[php5.6-fpm]=php5.6-fpm; ___app_related_services_order+=('php5.6-fpm');
___app_related_services[php7.0-fpm]=php7.0-fpm; ___app_related_services_order+=('php7.0-fpm');
___app_related_services[php7.0-fpm]=php7.1-fpm; ___app_related_services_order+=('php7.1-fpm');

___app_related_services[nginx]=nginx; ___app_related_services_order+=('nginx');
___app_related_services[apache2]=apache2; ___app_related_services_order+=('apache2');

# Stop app-related services.

function stop-app-related-services() {
  local _i _binary _service;

  for ((_i=${#___app_related_services_order[@]}-1; _i >= 0; _i--)); do
    _binary="${___app_related_services_order[$_i]}";
    _service="${___app_related_services[$_binary]}";

    if [[ "${_binary}" == 'discourse' ]]; then
      if [[ -x /discourse/launcher ]]; then
        /discourse/launcher stop app || true;
      fi;
    elif can-run "${_binary}"; then
      service "${_service}" stop &>/dev/null || true;
    fi;
  done;
};

# Start (or restart) app-related services.

function restart-app-related-services() {
  local _i _binary _service;

  for ((_i=0; _i < ${#___app_related_services_order[@]}; _i++)); do
    _binary="${___app_related_services_order[$_i]}";
    _service="${___app_related_services[$_binary]}";

    if [[ "${_binary}" == 'discourse' ]]; then
      if [[ -x /discourse/launcher ]]; then
        /discourse/launcher restart app;
      fi;
    elif can-run "${_binary}"; then
      service "${_service}" restart &>/dev/null;
    fi;
  done;
};

# Auto-restart app-related services on error.
# e.g., `trap auto-restart-app-related-services-on-error ERR;`

function auto-restart-app-related-services-on-error() {
  set +o xtrace; # Disable.
  restart-app-related-services;
  stack-trace "$@";
};

# Auto-warn user about app-related services on error.
# e.g., `trap auto-warn-about-app-related-services-on-error ERR;`

function auto-warn-about-app-related-services-on-error() {
  set +o xtrace; # Disable; i.e., turn off comand printing.
  echo '----------------------------------------------------------------------';
  echo 'WARNING: App-related services may still be in a stopped state, due to an error.';
  stack-trace "$@";
};
