#!/usr/bin/env bash

# Stop app-related services.

function stop-app-related-services() {
  local _binary _service;
  declare -A services;

  services[nginx]=nginx;
  services[apache2]=apache2;

  services[php-fpm]=php-fpm;
  services[php5-fpm]=php5-fpm;
  services[php-fpm7.0]=php7.0-fpm;

  services[mysql]=mysql;

  services[memcached]=memcached;

  services[discourse]=discourse;
  services[docker]=docker;

  services[fail2ban-client]=fail2ban;
  services[ufw]=ufw;

  services[postfix]=postfix;

  services[ssh]=ssh;

  for _binary in "${!services[@]}"; do
    _service="${services[$_binary]}";

    if [[ "${_binary}" == 'discourse' ]]; then
      if [[ -x /discourse/launcher ]]; then
        /discourse/launcher stop app || true;
      fi;
    elif can-run "${_binary}"; then
      service "${_service}" stop &>/dev/null || true;
    fi;
  done;
};

# Start (or restart) app-related services.

function restart-app-related-services() {
  local _binary _service;
  declare -A services;

  services[ssh]=ssh;

  services[postfix]=postfix;

  services[ufw]=ufw;
  services[fail2ban-client]=fail2ban;

  services[docker]=docker;
  services[discourse]=discourse;

  services[memcached]=memcached;

  services[mysql]=mysql;

  services[php-fpm7.0]=php7.0-fpm;
  services[php5-fpm]=php5-fpm;
  services[php-fpm]=php-fpm;

  services[apache2]=apache2;
  services[nginx]=nginx;

  for _binary in "${!services[@]}"; do
    _service="${services[$_binary]}";

    if [[ "${_binary}" == 'discourse' ]]; then
      if [[ -x /discourse/launcher ]]; then
        /discourse/launcher restart app;
      fi;
    elif can-run "${_binary}"; then
      service "${_service}" restart &>/dev/null;
    fi;
  done;
};

# Auto-restart app-related services on error.
# e.g., `trap auto-restart-app-related-services-on-error ERR;`

function auto-restart-app-related-services-on-error() {
  set +o xtrace; # Disable.
  restart-app-related-services;
  stack-trace "$@";
};

# Auto-warn user about app-related services on error.
# e.g., `trap auto-warn-about-app-related-services-on-error ERR;`

function auto-warn-about-app-related-services-on-error() {
  set +o xtrace; # Disable; i.e., turn off comand printing.
  echo '----------------------------------------------------------------------';
  echo 'WARNING: App-related services may still be in a stopped state, due to an error.';
  stack-trace "$@";
};
