#!/usr/bin/env bash

# Create admin utility.

function create-admin() {
  # Initialize.

  local user='';
  local pass='';
  local salt='';
  local pepper='';

  # Parse options.

  local short_options='u:p:s:r:';
  local long_options='user:,pass:,salt:,pepper:';
  local options; options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";

  eval set -- "${options}"; while true; do
     case "${1}" in
        -u|--user)
          user="${2}";
          shift 2;
          ;;
        -p|--pass)
          pass="${2}";
          shift 2;
          ;;
        -s|--salt)
          salt="${2}";
          shift 2;
          ;;
        -r|--pepper)
          pepper="${2}";
          shift 2;
          ;;
        --) shift 1; break;
          ;;
        *) echo 'Internal error.'; exit 1;
          ;;
     esac;
  done;

  if [[ -z "${pass}" ]]; then
    pass="$(passgen --salt="${salt}" --pepper="${pepper}" 15)";
  fi; # The `salt` & `pepper` are optional.

  # Create.

  create-user \
    --user="${user}" \
    --pass="${pass}";

  # Web-based tools auth.

  if [[ "${user}" != 'root' && "${user}" != 'vagrant' && "${user}" != 'ubuntu' ]]; then
    mkdir --parents /etc/bootstrap/passwds;
    touch /etc/bootstrap/passwds/.tools;

    htpasswd -D /etc/bootstrap/passwds/.tools "${user}" &>/dev/null;
    htpasswd -b /etc/bootstrap/passwds/.tools "${user}" "${pass}";
  fi;
};
