#!/usr/bin/env bash

# Create admin utility.

function create-admin() {
  # Initialize.

  local user='';
  local pass='';

  # Parse options.

  local short_options='u:p:';
  local long_options='user:,pass:';
  local options; options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";

  eval set -- "${options}"; while true; do
     case "${1}" in
        -u|--user)
          user="${2}";
          shift 2;
          ;;
        -p|--pass)
          pass="${2}";
          shift 2;
          ;;
        --) shift 1; break;
          ;;
        *) echo 'Internal error.'; exit 1;
          ;;
     esac;
  done;

  if [[ -z "${pass}" ]]; then
    pass="$(keygen 15)"; fi;

  # Create.

  create-user \
    --user="${user}" \
    --pass="${pass}";

  # Web-based tools auth.

  if [[ "${user}" != 'root' ]]; then
    mkdir --parents /etc/bootstrap/passwds;
    touch /etc/bootstrap/passwds/.tools;

    htpasswd -D /etc/bootstrap/passwds/.tools "${user}" &>/dev/null;
    htpasswd -cb /etc/bootstrap/passwds/.tools "${user}" "${pass}";
  fi;
};
