#!/usr/bin/env bash

# Create user utility.

function create-user() {
  # Initialize.

  local user='';
  local pass='';

  # Parse options.

  local short_options='u:p:';
  local long_options='user:,pass:';
  local options; options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";

  eval set -- "${options}"; while true; do
     case "${1}" in
        -u|--user)
          user="${2}";
          shift 2;
          ;;
        -p|--pass)
          pass="${2}";
          shift 2;
          ;;
        --) shift 1; break;
          ;;
        *) echo 'Internal error.'; exit 1;
          ;;
     esac;
  done;

  if [[ -z "${pass}" ]]; then
    pass="$(passgen 15)";
  fi;

  # Validate options.

  if [[ -z "${user}" || -z "${pass}" ]]; then
    return 1; fi; # Missing required arg(s).

  if user-exists "${user}"; then
    return 1; fi; # User exists!

  # Create user & set pass.

  if group-exists "${user}"; then
    useradd "${user}" -g "${user}" --create-home;
  else # Create a group matching the username.
    useradd "${user}" --user-group --create-home;
  fi;
  echo "${user}"':'"${pass}" | chpasswd;
};
