#!/usr/bin/env bash

# DigitalOcean metadata.

function do-region() {
  curl --silent --fail http://169.254.169.254/metadata/v1/region;
};

function do-droplet-id() {
  curl --silent --fail http://169.254.169.254/metadata/v1/id;
};

function do-mac-address() {
  curl --silent --fail http://169.254.169.254/metadata/v1/interfaces/public/0/mac;
};

function do-hostname() {
  curl --silent --fail http://169.254.169.254/metadata/v1/hostname;
};

function do-anchor-ip() {
  curl --silent --fail http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/address;
};

function do-public-ip() {
  curl --silent --fail http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address;
};

function do-public-ipv6() {
  curl --silent --fail http://169.254.169.254/metadata/v1/interfaces/public/0/ipv6/address;
};

function do-floating-ip() {
  curl --silent --fail http://169.254.169.254/metadata/v1/floating_ip/ipv4/ip_address;
};
function do-has-floating-ip() {
  if [[ "$(curl --silent --fail http://169.254.169.254/metadata/v1/floating_ip/ipv4/active)" == 'true' ]]; then
    return 0; # Has a floating IP.
  else # 1 = false.
    return 1;
  fi;
};
