#!/usr/bin/env bash

# GitHub issue URL.

function git-github-issue-url() {
  local owner="${1:-}";
  local slug="${2:-}";
  local issue="${3:-}";

  if [[ -z "${owner}" || -z "${slug}" || -z "${issue}" || ! "${issue}" =~ ^[1-9][0-9]*$ ]]; then
    echo 'Invalid input parameters. Unable to generate GitHub issue URL.';
    exit 1; fi; # Error status.

  echo 'https://github.com/'"${owner}"'/'"$(echo "${slug}" | perl -wpe 's/\-pro$//ui')"'/issues/'"${issue}";
};
