#!/usr/bin/env bash

# Git tree directory.

function git-tree-dir() {
  local dir=''; # Initialize.
  dir="$(git rev-parse --show-toplevel 2>/dev/null)";

  if [[ -z "${dir}" || ! -d "${dir}" ]]; then
    return 1; # Error status.
  fi;
  echo "${dir}";
};
