#!/usr/bin/env bash

# Git current branch.

function git-current-branch() {
  local branch=''; # Initialize.
  branch="$(git symbolic-ref --short --quiet HEAD 2>/dev/null)";

  if [[ -z "${branch}" ]]; then
    return 1; # Error status.
  fi;
  echo "${branch}";
};
