#!/usr/bin/env bash

# Git remote branch exists?

function git-remote-branch-exists() {
  if [[ -z "${1:-}" ]]; then
    return 1; # Not possible.
  fi;
  git ls-remote --exit-code origin refs/heads/"${1}" &>/dev/null;
};
