#!/usr/bin/env bash

# Git tree directory.

function git-tree-dir() {
  local dir=''; # Initialize.
  dir="$(git rev-parse --show-toplevel 2>/dev/null)";

  if [[ -z "${dir}" || ! -d "${dir}" ]]; then
    echo 'Failed to acquire git tree directory.';
    exit 1; fi; # Error status;

  echo "${dir}"; # Return tree directory.
};
