#!/usr/bin/env bash

# Git current branch.

function git-current-branch() {
  local branch=''; # Initialize.
  branch="$(git symbolic-ref --short --quiet HEAD 2>/dev/null)";

  if [[ -z "${branch}" ]]; then
    echo 'Failed to acquire current git branch.';
    exit 1; fi; # Error status;

  echo "${branch}"; # Return current branch name.
};
