#!/usr/bin/env bash

# Username/password valid?

function is-htpasswd-valid() {
  local user="${1:-}";
  local pass="${2:-}";

  if htpasswd -b -v /etc/bootstrap/passwds/.tools "${user}" "${user}" &>/dev/null; then
    return 0;
  else # 1 = false.
    return 1;
  fi;
};
