#!/usr/bin/env bash

# Gateway IP address.

function gateway-ip() {
  route -n | awk '/\s+UG\s+/{print $2}';
};

# Default interface name.

function default-interface() {
  local route;
  route=($(ip route | grep default));
  echo "${route[4]}"; # e.g., `eth0`
};
