#!/usr/bin/env bash

# Enable maintenance mode.

function enable-app-maintenance-mode() {
  touch /app/.~maintenance;
};

# Disable maintenance mode.

function disable-app-maintenance-mode() {
  rm --force /app/.~maintenance;
  can-run cachetool && cachetool opcache:reset;
  return 0; # In case last test fails.
};

# Auto-disable maintenance mode on error.
# e.g., `trap auto-disable-app-maintenance-mode-on-error ERR;`

function auto-disable-app-maintenance-mode-on-error() {
  set +o xtrace; # Disable.
  disable-app-maintenance-mode;
  stack-trace "$@";
};

# Auto-warn user about maintenance mode on error.
# e.g., `trap auto-warn-about-app-maintenance-mode-on-error ERR;`

function auto-warn-about-app-maintenance-mode-on-error() {
  set +o xtrace; # Disable; i.e., turn off comand printing.
  echo '----------------------------------------------------------------------';
  echo 'WARNING: The app may still be in maintenance mode due to an error.';
  echo '----------------------------------------------------------------------';
  stack-trace "$@";
};
