#!/usr/bin/env bash

# Enable maintenance mode.

function enable-app-maintenance-mode() {
  touch /app/.~maintenance;
};

# Disable maintenance mode.

function disable-app-maintenance-mode() {
  rm --force /app/.~maintenance;
  can-run cachetool && cachetool opcache:reset;
  return 0; # In case last test fails.
};

# Auto-disable maintenance mode on error.

function auto-disable-app-maintenance-mode-on-error() {
  disable-app-maintenance-mode; stack_trace "$@";
}; # e.g., `trap auto-disable-app-maintenance-mode-on-error ERR;`
