#!/usr/bin/env bash

# Restart app-related services.

function restart-app-related-services() {
  can-run mysql && service mysql restart &>/dev/null;
  can-run postfix && service postfix restart &>/dev/null;
  can-run memcached && service memcached restart &>/dev/null;

  can-run php-fpm && service php-fpm restart &>/dev/null;
  can-run php5-fpm && service php5-fpm restart &>/dev/null;
  can-run php-fpm7.0 && service php7.0-fpm restart &>/dev/null;

  can-run nginx && service nginx restart &>/dev/null;
  can-run apache2 && service apache2 restart &>/dev/null;

  can-run ssh && service ssh restart &>/dev/null;
  can-run ufw && service ufw restart &>/dev/null;
  can-run fail2ban-client && service fail2ban restart &>/dev/null;
};
