#!/usr/bin/env bash

# A `service` alternative.

function runit-service() {
  local exit_status;
  local service="${1:-}";
  local operation="${2:-}";

  if in-docker && can-run sv && [[ -x /etc/service/"${service}"/run ]]; then
    sv "${operation}" "${service}"; exit_status=$?;

    if [[ "${operation}" == 'start' || "${operation}" == 'restart' ]]; then
      sleep 5; fi; # Give the service time to startup.

    return "${exit_status}";

  elif in-docker && can-run sv && [[ "${service}" == 'ssh' ]]; then
    # Disabled in a Docker container.
    return 0; # Ignore silently.

  else return 1; fi; # Failure.
};
function maybe-add-runit-service() {
  local service="${1:-}";

  if in-docker && can-run sv && [[ -x /bootstrap/src/docker/runit/"${service}" ]]; then
    mkdir --parents /etc/service/"${service}";
    ln --symbolic --force /bootstrap/src/docker/runit/"${service}" /etc/service/"${service}"/run;
    sleep 5; # Give RUnit time to discover the new service.
  fi;
};
