#!/usr/bin/env bash

# A `service` alternative.

function runit-service() {
  local service="${1:-}";
  local operation="${2:-}";

  if in-docker && can-run sv && [[ -x /etc/service/"${service}"/run ]]; then
    sv "${2:-}" "${1:-}"; # See: <http://smarden.org/runit/sv.8.html>

  elif [[ "${service}" == 'ssh' ]]; then
    # Disabled in a Docker container.
    return 0; # Ignore silently.

  else return 1; fi; # Failure.
};
function maybe-add-runit-service() {
  local service="${1:-}";

  if in-docker && can-run sv && [[ -x /bootstrap/src/docker/runit/"${service}" ]]; then
    mkdir --parents /etc/sv/"${service}";
    ln --symbolic --force /bootstrap/src/docker/runit/"${service}" /etc/sv/"${service}"/run;
    ln --symbolic --force /etc/sv/"${service}" /etc/service/"${service}"; # Enable.
  fi;
};
