#!/usr/bin/env bash

# Trim utility.

function trim() {
  local chars;

  if [[ -p /dev/stdin ]]; then
    if [[ -n "${1:-}" ]]; then
      chars="$(esc-regex "${1}")";
      echo -n "$(perl -0wpe 's/(^['"${chars}"']+|['"${chars}"']+$)//ug')";
    else
      echo -n "$(perl -0wpe 's/(^\s+|\s+$)//ug')";
    fi;
  else
    if [[ -n "${2:-}" ]]; then
      chars="$(esc-regex "${2}")";
      echo -n "$(echo "${1:-}" | perl -0wpe 's/(^['"${chars}"']+|['"${chars}"']+$)//ug')";
    else
      echo -n "$(echo "${1:-}" | perl -0wpe 's/(^\s+|\s+$)//ug')";
    fi;
  fi;
};
