#!/usr/bin/env bash

# Sanity check. Running as sudo?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Trap errors & warn the user if an error occurs.

if [[ -d /repos/app.git ]]; then
  find /repos/app.git -type d -exec chmod 2775 {} \;
  find /repos/app.git -type f -exec chmod 664 {} \;
fi;

if [[ -d /app/src/vendor ]]; then
  find /app/src/vendor -type d -exec chmod 2775 {} \;
  find /app/src/vendor -type f -exec chmod 664 {} \;
fi;

if [[ -d /tmp/.websharks ]]; then
  chmod 777 /tmp/.websharks;
fi;
if [[ -d /tmp/.websharks/phings ]]; then
  chmod 777 /tmp/.websharks/phings;
fi;
