#!/usr/bin/env bash

if [[ "${CFG_INSTALL_APP_REPO}" == 1 ]]; then

  # Create directory.

  mkdir --parents /repos/app.git;

  # Configure repo.

  git init --bare /repos/app.git;
  git --git-dir=/repos/app.git symbolic-ref HEAD refs/heads/master;
  ln --symbolic --force /bootstrap/assets/git/repos/app/hooks/post-receive /repos/app.git/hooks/post-receive;

  # Set permissions for files in the app & repo directories.

  chown --recursive www-data:www-data /repos/app.git;
  chmod g+s /repos/app.git; # Stick w/ this group.
  # NOTE: Users & app should have a umask of 0002.

  find /repos/app.git -type d -exec chmod 775 {} \;
  find /repos/app.git -type f -exec chmod 664 {} \;

else echo 'Skipping app repo installation.'; fi;
