#!/usr/bin/env bash

# Cleanup archives.

if ! is-vagrant; then
  apt-get clean --yes;
fi;

# Remove root SSH key (security).

rm --force /root/.ssh/id_rsa;
rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/id_rsa;
