#!/usr/bin/env bash

# Grand finale.

echo '-- Bootstrap installation complete. ------';

# Suggest a reload of current login shell.

echo 'Log out & back in. Or type: `'"$(basename "${CFG_ADMIN_PREFERRED_SHELL}")"' -l` to reload shell.';
