#!/usr/bin/env bash

if can_run php; then

  # Install Phing for PHP.

  curl http://www.phing.info/get/phing-latest.phar \
    --output /usr/bin/phing; # Save as binary.

  chmod +x /usr/bin/phing; # Make it executable.

else echo 'Skipping Phing installation.'; fi;
