#!/usr/bin/env bash

if [[ "${CFG_INSTALL_RAMDISK}" == 1 ]]; then

  # Mount a RAM disk partition.

  mkdir --parents /ramdisks/app;
  echo 'tmpfs /ramdisks/app tmpfs defaults,size=33%,uid=nobody,gid=app,mode=2775 0 0' >> /etc/fstab;
  mount -a; # Mount the new partition.

else echo 'Skipping RAM disk installation.'; fi;
