#!/usr/bin/env bash

# Maybe harden SSH security.

if ! is-vagrant; then # If NOT on a vagrant box.

  perl -i -wpe 's/^(\s*)PermitRootLogin\s+.*$/$1PermitRootLogin no/uim' /etc/ssh/sshd_config;
  echo '# Allow Specific Groups Only' >> /etc/ssh/sshd_config;
  echo 'AllowGroups sudo ssh-access' >> /etc/ssh/sshd_config;

  # See <http://en.wikibooks.org/wiki/OpenSSH/Cookbook/SFTP>
  # addgroup sftp-only; # Already done in: `assets/setups/users`

  echo '# SFTP Only Group Restrictions' >> /etc/ssh/sshd_config;
  echo 'Match Group sftp-only' >> /etc/ssh/sshd_config;
  echo '    AllowTCPForwarding no' >> /etc/ssh/sshd_config;
  echo '    X11Forwarding no' >> /etc/ssh/sshd_config;
  echo '    ForceCommand internal-sftp' >> /etc/ssh/sshd_config;

  perl -i -wpe 's/^(\s*)Subsystem\s+sftp\s+.*$/$1Subsystem sftp internal-sftp/uim' /etc/ssh/sshd_config;

  service ssh restart;

else echo 'Skipping SSH configuration & security hardening.'; fi;
