#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Maybe run setup routines; i.e., once only.

if [[ ! -f /etc/bootstrap/.installed ]]; then

  export CFG_IS_INSTALLER='1';
  export CFG_IS_UPDATER='0';

  export CFG_INSTALLED_VERSION='';

  . /bootstrap/src/setups/cfgs-args;
  . /bootstrap/src/setups/config;

  set -o xtrace; # Print each command that is run.
  umask 0002; # Force this default during installation.

  . /bootstrap/src/setups/runit;
  . /bootstrap/src/setups/debian;
  . /bootstrap/src/setups/aptitude;
  . /bootstrap/src/setups/timezone;

  . /bootstrap/src/setups/utilities;
  . /bootstrap/src/setups/git-utils;
  . /bootstrap/src/setups/keybase;

  . /bootstrap/src/setups/swap;

  . /bootstrap/src/setups/zsh;
  . /bootstrap/src/setups/hosts;
  . /bootstrap/src/setups/users;
  . /bootstrap/src/setups/mkdirs;
  . /bootstrap/src/setups/umask;

  . /bootstrap/src/setups/git-up;

  . /bootstrap/src/setups/env-vars;
  . /bootstrap/src/setups/ssl-certs;
  . /bootstrap/src/setups/htpasswd;

  . /bootstrap/src/setups/docker;

  . /bootstrap/src/setups/postfix;

  . /bootstrap/src/setups/nginx;
  . /bootstrap/src/setups/apache;

  . /bootstrap/src/setups/mysql;

  . /bootstrap/src/setups/ramdisk;
  . /bootstrap/src/setups/memcache;

  . /bootstrap/src/setups/php/stub;

  . /bootstrap/src/setups/phpcs;
  . /bootstrap/src/setups/phing;
  . /bootstrap/src/setups/phpunit;
  . /bootstrap/src/setups/casperjs;
  . /bootstrap/src/setups/composer;
  . /bootstrap/src/setups/wp-cli;
  . /bootstrap/src/setups/wsc;

  . /bootstrap/src/setups/app-repo;
  . /bootstrap/src/setups/discourse;
  . /bootstrap/src/setups/wordpress;

  . /bootstrap/src/setups/ssh-config;
  . /bootstrap/src/setups/firewall;
  . /bootstrap/src/setups/fail2ban;

  . /bootstrap/src/setups/resources;

  if [[ -f /bootstrap-app/post-install ]]; then
    . /bootstrap-app/post-install; fi;

  . /bootstrap/src/version; # Update.
  CFG_INSTALLED_VERSION="${CFG_VERSION}";
  echo "${CFG_VERSION}" > /etc/bootstrap/.installed;

  . /bootstrap/src/setups/cleanup;

  set +o xtrace; # Turn off comand printing.

  . /bootstrap/src/setups/finale;

else # Provide details about why we are not running again.
  echo 'Installation complete. Can only be run once!'; exit 1;
fi; # End `.installed` check.
