#!/usr/bin/env bash

# Running as root?

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Trap errors & warn the user if an error occurs.

trap auto-warn-about-app-related-services-on-error ERR;

# Maybe run update routines; i.e., if installed already.

if [[ -f /etc/bootstrap/.installed ]]; then

  export CFG_IS_INSTALLER='0';
  export CFG_IS_UPDATER='1';

  export CFG_INSTALLED_VERSION; # Read file.
  CFG_INSTALLED_VERSION="$(cat /etc/bootstrap/.installed)";

  set -o xtrace; # Print each command that is run.

  stop-app-related-services; # Stop while updating.

  . /bootstrap/src/setups/repos-up;
  . /bootstrap/src/setups/vs-ups;

  if [[ -f /bootstrap-app/src/post-update ]]; then
    . /bootstrap-app/src/post-update; fi;

  . /bootstrap/src/version; # Update.
  CFG_INSTALLED_VERSION="${CFG_VERSION}";
  echo "${CFG_VERSION}" > /etc/bootstrap/.installed;

  . /bootstrap/src/setups/cleanup;

  restart-app-related-services;

  set +o xtrace; # Turn off comand printing.

  . /bootstrap/src/setups/finale;

else # Provide details about why we are not updating.
  echo 'Not installed yet. Run the installer first please!'; exit 1;
fi; # End `.installed` check.
