#!/usr/bin/env bash

if [[ "${CFG_INSTALL_PHP_CLI}" == 1 || "${CFG_INSTALL_PHP_FPM}" == 1 ]]; then

  # Install PHP CLI and/or PHP process manager.

  if [[ "${CFG_INSTALL_PHP_VERSION}" == 7.0 ]]; then
    . /bootstrap/src/setups/php/via-ppa/v7.0;

  elif [[ "${CFG_INSTALL_PHP_VERSION}" == 5.6 ]]; then
    . /bootstrap/src/setups/php/via-ppa/v5.6;

  elif [[ "${CFG_INSTALL_PHP_VERSION}" == 5.5 ]]; then
    . /bootstrap/src/setups/php/via-ppa/v5.5;

  elif [[ "${CFG_INSTALL_PHP_VERSION}" == 5.4 ]]; then
    . /bootstrap/src/setups/php/via-ppa/v5.4;

  elif [[ "${CFG_INSTALL_PHP_VERSION}" =~ ^custom ]]; then
    . /bootstrap/src/setups/php/custom;
  fi;

else echo 'Skipping PHP installation.'; fi;
