#!/usr/bin/env bash

if [[ ( "${CFG_INSTALL_PHP_CLI}" == 1 || "${CFG_INSTALL_PHP_FPM}" == 1 ) && "${CFG_INSTALL_PHP_VERSION}" =~ ^@TODO_custom ]]; then

  ## Enable the igbinary extension. @TODO Once it supports PHP7.

  echo 'extension=igbinary.so' > /etc/php/conf.d/igbinary.ini;

  if [[ "${CFG_INSTALL_PHP_CLI}" == 1 ]]; then
    ln --symbolic /etc/php/conf.d/igbinary.ini /etc/php/cli/conf.d/igbinary.ini; fi;

  if [[ "${CFG_INSTALL_PHP_FPM}" == 1 ]]; then
    ln --symbolic /etc/php/conf.d/igbinary.ini /etc/php/fpm/conf.d/igbinary.ini;
    service php-fpm restart; # Restart service.
  fi;

else echo 'Skipping igBinary extension for custom PHP.'; fi;
