#!/usr/bin/env bash

if [[ ( "${CFG_INSTALL_PHP_CLI}" == 1 || "${CFG_INSTALL_PHP_FPM}" == 1 ) && "${CFG_INSTALL_PHP_VERSION}" =~ ^custom ]]; then

  ## Enable the Memcached extension.

  echo 'extension=memcached.so' > /etc/php/conf.d/memcached.ini;

  if [[ "${CFG_INSTALL_PHP_CLI}" == 1 ]]; then
    ln --symbolic /etc/php/conf.d/memcached.ini /etc/php/cli/conf.d/memcached.ini; fi;

  if [[ "${CFG_INSTALL_PHP_FPM}" == 1 ]]; then
    ln --symbolic /etc/php/conf.d/memcached.ini /etc/php/fpm/conf.d/memcached.ini;
    service php-fpm restart; # Restart service.
  fi;

else echo 'Skipping Memcached extension for custom PHP.'; fi;
