#!/usr/bin/env bash

if [[ ( "${CFG_INSTALL_PHP_CLI}" == 1 || "${CFG_INSTALL_PHP_FPM}" == 1 ) && "${CFG_INSTALL_PHP_VERSION}" =~ ^custom ]]; then

  ## Enable the OPcache extension.

  echo 'zend_extension=opcache.so' > /etc/php/conf.d/opcache.ini;

  if [[ "${CFG_INSTALL_PHP_CLI}" == 1 ]]; then
    ln --symbolic /etc/php/conf.d/opcache.ini /etc/php/cli/conf.d/opcache.ini; fi;

  if [[ "${CFG_INSTALL_PHP_FPM}" == 1 ]]; then
    ln --symbolic /etc/php/conf.d/opcache.ini /etc/php/fpm/conf.d/opcache.ini;
    service php-fpm restart; # Restart service.
  fi;

else echo 'Skipping OPcache extension for custom PHP.'; fi;
