#!/usr/bin/env bash

# Install deps.

. /bootstrap/src/setups/utils/deps/_stub;

# Install utilities.

. /bootstrap/src/setups/utils/arc-tools;
. /bootstrap/src/setups/utils/auth-tools;
. /bootstrap/src/setups/utils/disk-tools;
. /bootstrap/src/setups/utils/doc-tools;
. /bootstrap/src/setups/utils/enc-tools;
. /bootstrap/src/setups/utils/health-tools;
. /bootstrap/src/setups/utils/media-tools;
