#!/usr/bin/env bash

apt-get install build-essential --yes;

apt-get install g++ --yes;
apt-get install cmake --yes;
apt-get install libtool --yes;
apt-get install autoconf --yes;
apt-get install pkg-config --yes;
