#!/usr/bin/env bash

# Grand finale; update complete.

echo '---------------------------------------------------------------';
echo '-- Bootstrap update complete. ---------------------------------';
echo '---------------------------------------------------------------';
echo '  Log out & back in again to reload shell.';
