#!/usr/bin/env bash

# Update bootstrap repo.

bootstrap-repo-update /bootstrap https://github.com/websharks/ubuntu-bootstrap master;

# Update the websharks/core repo.

if [[ -d /usr/local/src/websharks-core ]]; then
  cd /usr/local/src/websharks-core;

  git pull; # Merge latest changes.
  git submodule update --recursive --force --init;
  phing post-receive-build;
fi;
